import type { GuidePost } from "./posts";

export const linkResourceGuidePosts: GuidePost[] = [
  {
    slug: "akut-elfel-hemma-forsta-minuterna",
    title: "Akut elfel hemma – första 5 minuterna",
    description: "En tydlig steg-för-steg-guide för bränd lukt, rök, strömgenomgång, gnistor och andra akuta elfel i hemmet.",
    category: "Akut elsäkerhet",
    readTime: "6 min läsning",
    publishedAt: "2026-08-24",
    updatedLabel: "Uppdaterad 24 augusti 2026",
    accent: "red",
    intro: "När något händer med elen hemma är de första minuterna viktiga. Målet är inte att felsöka färdigt själv, utan att minska risken för personskada, brand och nya farliga situationer tills rätt hjälp kan ta över.",
    safetyNote: "Ring 112 direkt vid brand, rök, personskada, ström genom kroppen eller om du inte kan lämna situationen säkert.",
    sections: [
      { heading: "Börja med säkerheten", paragraphs: ["Håll avstånd från det som ryker, gnistrar, luktar bränt eller kan vara spänningssatt. Rör inte en person som fortfarande kan ha kontakt med ström. Om du kan bryta strömmen utan risk kan du göra det, men gå inte nära en pågående brand eller ett skadat område."], steps: ["Håll avstånd.", "Larma andra i bostaden.", "Bryt strömmen bara om det kan göras säkert.", "Ring 112 vid akut fara.", "Vänta inte med hjälp om någon fått ström genom kroppen."] },
      { heading: "När ska du ringa 112?", paragraphs: ["Ring 112 om det finns rök, lågor, kraftig bränd lukt, gnistor, en personskada eller misstanke om strömgenomgång. Säg tydligt att det gäller el, var i bostaden problemet finns och om strömmen är bruten eller inte."] },
      { heading: "När ska du kontakta elektriker?", paragraphs: ["Kontakta elektriker när felet gäller elcentral, fasta kablar, vägguttag, strömbrytare, laddbox, golvvärme eller återkommande säkringsproblem. Använd inte samma uttag, grupp eller produkt igen bara för att felet verkar ha försvunnit."] },
      { heading: "Spara rätt information", paragraphs: ["När läget är säkert kan du notera vad som hände: tidpunkt, ljud, lukt, vilken produkt som användes, om säkring eller jordfelsbrytare löste ut och om något blev varmt eller missfärgat. Den informationen gör första bedömningen snabbare."], steps: ["Beskriv symtomet.", "Fotografera på avstånd om det är säkert.", "Säg om strömmen är bruten.", "Berätta om barn, äldre eller husdjur finns i bostaden."] },
    ],
    sourceLabel: "Elsäkerhetsverket: Vad gör jag vid en elolycka?",
    sourceUrl: "https://www.elsakerhetsverket.se/privatpersoner/om-du-drabbas-av-en-elolycka/vad-gor-jag-vid-en-elolycka/",
  },
  {
    slug: "checklista-elfel-hemma",
    title: "Checklista vid elfel hemma – kontrollera utan att ta risker",
    description: "En praktisk checklista för varningssignaler som bränd lukt, varma uttag, återkommande säkringsfel och otydlig elcentral.",
    category: "Elsäkerhet hemma",
    readTime: "7 min läsning",
    publishedAt: "2026-08-24",
    updatedLabel: "Uppdaterad 24 augusti 2026",
    accent: "blue",
    intro: "Den här checklistan är tänkt som en trygg första genomgång när något känns fel med elen hemma. Den hjälper dig att samla observationer utan att öppna elcentral, uttag eller produkter.",
    safetyNote: "Avbryt checklistan vid rök, gnistor, bränd lukt, stark värme eller personskada. Prioritera avstånd, 112 vid akut fara och professionell hjälp.",
    sections: [
      { heading: "Titta, lyssna och lukta", paragraphs: ["Elsäkerhetsverket rekommenderar att du använder dina sinnen vid kontroll av elanläggningen. Leta efter missfärgningar, sprickor, ovanliga ljud, värme och lukt av bränt. Rör inte delar som verkar skadade eller varma."], steps: ["Finns bränd lukt?", "Syns missfärgning eller smält plast?", "Hörs surr, knaster eller sprak?", "Känns uttag, propphuv eller stickpropp onormalt varm?"] },
      { heading: "Avgränsa utan att öppna något", paragraphs: ["Notera om felet gäller hela bostaden, ett rum, en grupp eller en viss produkt. Om en säkring eller jordfelsbrytare löser ut igen efter återställning ska du inte fortsätta prova. Återkommande fel behöver felsökas."] },
      { heading: "Kontrollera dokumentationen", paragraphs: ["Se om gruppförteckningen är tydlig och om du vet vilken säkring som hör till vilket rum. Otydlig märkning är inte akut i sig, men den gör både egen kontroll och professionell felsökning svårare."] },
      { heading: "När checklistan ska bli en förfrågan", paragraphs: ["Kontakta elektriker om du hittar värme, lukt, missfärgning, sprickor, glapp, skadade kablar, återkommande frånslag eller otydlig central efter renovering. Skicka gärna en kort sammanfattning av punkterna ovan när du ber om hjälp."], steps: ["Beskriv platsen.", "Beskriv symtomet.", "Säg om felet återkommer.", "Bifoga bild på elcentral eller uttag om det kan göras säkert."] },
    ],
    sourceLabel: "Elsäkerhetsverket: Checklista för kontroll av elanläggning",
    sourceUrl: "https://www.elsakerhetsverket.se/privatpersoner/din-elanlaggning/kontrollera-din-elanlaggning/checklista-for-kontroll-av-elanlaggning/",
  },
  {
    slug: "elansvar-villa-bostadsratt-hyresratt",
    title: "Elansvar i villa, bostadsrätt och hyresrätt – vem gör vad?",
    description: "En översikt över vem som ansvarar för elfel, kontroll och beställning av elarbete i villa, bostadsrätt och hyresrätt.",
    category: "Elsäkerhet hemma",
    readTime: "7 min läsning",
    publishedAt: "2026-08-24",
    updatedLabel: "Uppdaterad 24 augusti 2026",
    accent: "green",
    intro: "När ett elfel uppstår är första frågan ofta vem som ska agera: du, hyresvärden, bostadsrättsföreningen eller ett registrerat elföretag. Ansvarsfördelningen påverkar både felanmälan, kostnad och hur snabbt rätt hjälp kopplas in.",
    safetyNote: "Oavsett boendeform ska akuta risker hanteras först. Ring 112 vid brand, rök, personskada eller om någon fått ström genom kroppen.",
    sections: [
      { heading: "Villa och fritidshus", paragraphs: ["Den som äger en villa eller ett fritidshus är normalt innehavare av elanläggningen och ansvarar för att den är säker, kontrolleras och används rätt. Fasta installationer som elcentral, ledningar, uttag och strömbrytare ska hanteras av rätt kompetens när arbete krävs."], steps: ["Spara dokumentation från elarbeten.", "Kontrollera synliga varningssignaler regelbundet.", "Anlita registrerat elföretag för fast installation."] },
      { heading: "Bostadsrätt", paragraphs: ["I bostadsrätt är ansvaret ofta delat. Föreningen ansvarar vanligtvis för fasta installationer i gemensamma utrymmen, medan bostadsrättshavaren ofta tar över ansvaret från lägenhetens elcentral. Stadgarna kan ändra gränsen, så kontrollera dem innan arbete beställs."], steps: ["Kontrollera föreningens stadgar.", "Felanmäl gemensamma delar till föreningen.", "Samordna vid laddbox, badrum eller större renovering."] },
      { heading: "Hyresrätt", paragraphs: ["I hyresrätt ska fel i den fasta elanläggningen normalt felanmälas till hyresvärden. Du ansvarar samtidigt för att använda dina egna elprodukter säkert och sluta använda produkter som glappar, luktar bränt eller beter sig fel."], },
      { heading: "Vem får göra elarbetet?", paragraphs: ["Vissa enklare arbeten får privatpersoner bara göra själva om de har tillräcklig kunskap. De flesta arbeten i fasta installationer ska utföras av ett registrerat elinstallationsföretag. Kontrollera företaget i Elsäkerhetsverkets tjänst Kolla elföretaget innan du beställer."], steps: ["Avgör om felet är i en produkt eller fast installation.", "Felanmäl till rätt ansvarig part.", "Kontrollera elföretaget innan beställning.", "Spara offert, dokumentation och gruppförteckning."] },
    ],
    sourceLabel: "Elsäkerhetsverket: Så tar du ditt ansvar för elen",
    sourceUrl: "https://www.elsakerhetsverket.se/privatpersoner/du-ar-ansvarig-for-elen/sa-tar-du-ditt-ansvar-for-elen/",
  },
];
