import type { GuidePost } from "./posts";

type NewGuidePost = Omit<GuidePost, "publishedAt" | "updatedLabel">;

function guide(post: NewGuidePost): GuidePost {
  return {
    ...post,
    publishedAt: "2026-08-17",
    updatedLabel: "Uppdaterad 17 augusti 2026",
  };
}

export const safetyGuidePosts: GuidePost[] = [
  guide({
    slug: "tillverka-egen-lampa-sakert",
    title: "Tillverka egen lampa – därför bör du tänka om före första kopplingen",
    description: "Egenbyggda lampor kan medföra brand- och elchocksrisk. Här är vad du behöver veta innan du börjar.",
    category: "Belysning",
    readTime: "5 min läsning",
    accent: "red",
    intro: "Att bygga en egen armatur kan se ut som ett enkelt hobbyprojekt, men resultatet blir en elektrisk produkt som måste vara säker i hela sin konstruktion. Elsäkerhetsverket rekommenderar att privatpersoner avstår från att tillverka egna armaturer, eftersom fel kan leda till elchock, brand eller störningar.",
    safetyNote: "Använd aldrig en hemmagjord lampa om du är osäker på konstruktionen. Ge inte bort eller sälj den – då tillkommer omfattande produktansvar.",
    sections: [
      { heading: "En ny armatur är mer än en lampfot", paragraphs: ["När sladd, lamphållare och kontakt sätts ihop med en egentillverkad fot uppstår en ny elektrisk produkt. Säkerheten handlar därför inte bara om att lampan lyser, utan också om isolering, dragavlastning, värme, skyddsklass och att alla delar fungerar tillsammans."] },
      { heading: "Varför färdiga delar inte räcker", paragraphs: ["Även om enskilda komponenter är köpta och märkta är kombinationen inte automatiskt säker. Tillverkaren av en färdig armatur ansvarar för konstruktion och kontroller. När du bygger själv behöver du kunna säkerställa motsvarande skydd i den färdiga produkten."], steps: ["Avstå från att koppla ihop lösa delar om du inte kan bedöma hela konstruktionen.", "Välj hellre en färdig, avsedd armatur.", "Ta trasiga eller osäkra lampor ur bruk i stället för att improvisera en lösning."] },
      { heading: "Eget bruk är inte samma sak som att överlåta", paragraphs: ["En egentillverkad lampa för eget bruk behöver inte CE-märkas, men den måste fortfarande vara säker. Om du säljer eller ger bort den behöver du som tillverkare bland annat bedöma överensstämmelse, CE-märka produkten, upprätta EU-försäkran och lämna svensk säkerhetsinformation."], },
      { heading: "Var särskilt försiktig med stickproppen", paragraphs: ["Byt inte skyddsklass på en äldre eller hemmabyggd lampa genom att sätta dit en annan typ av stickpropp. En jordad kontakt på en produkt som inte är konstruerad för skyddsjord kan ge en falsk bild av säkerheten. Låt en fackperson bedöma en befintlig lampa som behöver repareras."], },
    ],
    sourceLabel: "Elsäkerhetsverket: Tillverka lampor för eget bruk",
    sourceUrl: "https://www.elsakerhetsverket.se/privatpersoner/dina-elprodukter/tillverka-andra-och-laga-elprodukter/tillverka-lampor-for-eget-bruk/",
  }),
  guide({
    slug: "symbolen-dubbelisolerad-elprodukt",
    title: "Symbolen med två fyrkanter – så känner du igen en dubbelisolerad elprodukt",
    description: "Vad betyder två fyrkanter på en laddare eller lampa? Lär dig vad dubbelisolering visar och vad den inte säger.",
    category: "Elprodukter",
    readTime: "4 min läsning",
    accent: "blue",
    intro: "Två fyrkanter, en inuti den andra, är symbolen för dubbelisolering – även kallad isolationsklass II. Den förekommer ofta på mindre elprodukter och är en del av produktens säkerhetsmärkning. Symbolen hjälper dig att förstå hur produkten är konstruerad, men ersätter inte ett säkert användningssätt.",
    safetyNote: "Använd inte symbolen som ett skäl att fortsätta använda en skadad produkt. Sprucken isolering, glapp eller värmeskador betyder att produkten ska tas ur bruk.",
    sections: [
      { heading: "Så ser märkningen ut", paragraphs: ["Märkningen är en större fyrkant med en mindre fyrkant inuti. Elsäkerhetsverket beskriver den som en markering för dubbelisolering, eller isolationsklass II. Den kan sitta på produkten, märkplåten, nätadaptern eller i vissa fall på förpackningen om produkten är mycket liten."] },
      { heading: "Vad dubbelisolering innebär", paragraphs: ["Dubbelisolering är ett skydd i produktens konstruktion. Många sådana produkter har platt stickpropp, men det är produktens märkning och konstruktion som avgör skyddsklassen – inte bara hur kontakten ser ut."] },
      { heading: "Kontrollera mer än en symbol", paragraphs: ["När du köper eller använder en elprodukt ska du också kunna hitta typbeteckning, märkdata för spänning och ström, samt uppgifter om ansvarig tillverkare eller importör. Bruksanvisning och säkerhetsinformation ska finnas på svenska."], steps: ["Leta efter märkningen på produkten och laddaren.", "Kontrollera att produkten är avsedd för svenska elnätet.", "Spara anvisningen så att användning och skötsel kan följas."] },
      { heading: "När produkten ska tas ur bruk", paragraphs: ["Dubbelisolering är inte ett skydd mot slitage. Om höljet är trasigt, kabeln sprucken, stickproppen glappar eller produkten luktar bränt ska den inte användas. Kassera produkten eller låt en fackperson bedöma en möjlig reparation."], },
    ],
    sourceLabel: "Elsäkerhetsverket: Krav och märkning på elprodukter",
    sourceUrl: "https://www.elsakerhetsverket.se/privatpersoner/dina-elprodukter/krav-och-markning-pa-elprodukter/",
  }),
  guide({
    slug: "lampa-nara-gardin-eller-textil",
    title: "Lampa nära gardin eller säng – så minskar du brandrisken",
    description: "Heta lampor och textilier är en riskfylld kombination. Kontrollera placering, effekt och lampans skick hemma.",
    category: "Belysning",
    readTime: "4 min läsning",
    accent: "amber",
    intro: "En lampa som kommer nära gardiner, sängkläder eller annan textil kan skapa en onödigt riskfylld situation, särskilt om armaturen blir varm eller har fel ljuskälla. En enkel kontroll av placering, avstånd och märkning gör stor skillnad.",
    safetyNote: "Flytta undan textilier från en varm armatur. Använd aldrig en lampa som luktar bränt, blinkar, glappar eller har synliga värmeskador.",
    sections: [
      { heading: "Textilier ska inte nå lampan", paragraphs: ["Gardiner, filtar, sängkläder och annat brännbart material får inte komma i kontakt med heta lampor. Kontrollera också att luft kan cirkulera runt armaturen och att den inte täcks av textil eller placeras trångt bakom möbler."] },
      { heading: "Följ armaturens maxeffekt", paragraphs: ["Använd inte en ljuskälla med högre effekt än armaturens angivna maxvärde. Märkningen finns normalt på armaturen eller i anvisningen. En för stark lampa kan göra att värmen blir högre än konstruktionen är avsedd för."], steps: ["Läs maxeffekten på armaturen.", "Kontrollera att textilier hålls på avstånd.", "Släck och undersök placeringen om lampan blir ovanligt varm."] },
      { heading: "Blinkande ljus är en varningssignal", paragraphs: ["En lampa som blinkar eller fungerar onormalt kan ha glappkontakt. Elsäkerhetsverket pekar på att glapp kan medföra överhettning och brand. Prova inte att lösa problemet genom att vrida, böja eller tejpa en skadad del."], },
      { heading: "När du ska ta hjälp", paragraphs: ["Är armaturen fast ansluten, sitter en koppling löst eller finns det missfärgning och bränd lukt, ska du sluta använda den och låta ett registrerat elinstallationsföretag bedöma den fasta delen. Vid rök eller brand gäller 112."], },
    ],
    sourceLabel: "Elsäkerhetsverket: Kontrollera dina elprodukter",
    sourceUrl: "https://www.elsakerhetsverket.se/privatpersoner/dina-elprodukter/kontrollera-dina-elprodukter/",
  }),
  guide({
    slug: "sladd-mot-varmeelement-eller-ugn",
    title: "Sladd mot värmeelement eller ugn – därför kan isoleringen skadas",
    description: "En kabel som ligger mot värme kan få skadad isolering. Så kontrollerar du placeringen utan att ta risker.",
    category: "Sladdar",
    readTime: "4 min läsning",
    accent: "red",
    intro: "En sladd kan se hel ut men ändå påverkas av värme från element, varma lampor, spisar, ugnar eller varmvattenledningar. När isoleringen skadas kan den elektriska säkerheten försämras. Därför är kabeldragning en viktig del av den vanliga hemkontrollen.",
    safetyNote: "Flytta inte en kabel som är varm, smält, sprucken eller sitter fast mot en het yta. Koppla ur produkten om det kan göras säkert och använd den inte igen.",
    sections: [
      { heading: "Värme sliter på kabeln", paragraphs: ["Elsäkerhetsverket rekommenderar att du kontrollerar om sladdar kommer i kontakt med heta ytor. Hög värme kan skada isoleringen, även när kabeln inte direkt har smält. Titta därför efter missfärgning, sprickor, hård eller mjuk plast och andra förändringar."], },
      { heading: "Gå igenom vanliga riskplatser", paragraphs: ["Kontrollera bakom och runt spis, ugn, element, kylskåp, lampor och varmvattenledningar. Lägg inte laddkablar eller förlängningssladdar där de riskerar att hamna mot varma apparater när möbler flyttas eller köksutrustning används."], steps: ["Dra sladdar med avstånd till heta ytor.", "Se till att kabeln inte kan glida tillbaka mot värmen.", "Kontrollera regelbundet synliga delar av kabeln."] },
      { heading: "Ersätt inte med tejp", paragraphs: ["Tejp eller en provisorisk isolering återställer inte kabelns säkerhet. Använd inte en sladd med skadad isolering, och öppna inte en fast ansluten produkt eller installation för att reparera den själv."], },
      { heading: "Ta hjälp om den fasta elen berörs", paragraphs: ["Om kabeln hör till en fast ansluten apparat, går in i vägg eller har skadats nära en fast installation, ska ett registrerat elinstallationsföretag bedöma situationen. Vid rök, gnistor eller brand ska du hålla avstånd och ringa 112."], },
    ],
    sourceLabel: "Elsäkerhetsverket: Kontrollera dina elprodukter",
    sourceUrl: "https://www.elsakerhetsverket.se/privatpersoner/dina-elprodukter/kontrollera-dina-elprodukter/",
  }),
  guide({
    slug: "sladdharva-bakom-tv-och-dator",
    title: "Sladdhärva bakom tv eller dator – så minskar du risken för överhettning",
    description: "Täta kabelhärvor kan samla värme. Ordna tv-bänk och hemmakontor säkrare med en enkel kontroll.",
    category: "Sladdar",
    readTime: "4 min läsning",
    accent: "amber",
    intro: "Bakom tv-bänken och skrivbordet samlas ofta laddare, grenuttag och långa kablar. När belastade sladdar ligger tätt ihop kan värme byggas upp. En kabelhärva är därför inte bara svår att städa – den kan också göra det svårare att upptäcka skador och överhettning.",
    safetyNote: "Kedjekoppla inte grenuttag och täck inte över laddare eller grendosor med mattor, textilier eller möbler som stoppar ventilationen.",
    sections: [
      { heading: "Varför kabelhärvor kan bli varma", paragraphs: ["Elsäkerhetsverket varnar för större knippen av belastade sladdar eftersom värmen kan bli hög. Risken ökar när flera effektkrävande produkter delar samma plats eller när kablar ligger hoprullade och tätt packade."] },
      { heading: "Sortera utan att ändra installationen", paragraphs: ["Börja med att koppla ur utrustning som inte används och dra sedan kablar med luft mellan dem. Använd lagom långa kablar, håll dem synliga för kontroll och se till att stickproppar och uttag sitter ordentligt. Undvik att klämma kablar bakom tunga möbler."], steps: ["Koppla ur onödiga laddare och adaptrar.", "Räta ut kablar som ligger i täta nystan.", "Kontrollera att inga kontakter är varma, lösa eller missfärgade."] },
      { heading: "Belastning och ventilation hör ihop", paragraphs: ["En stor mängd elektronik på samma grenuttag kan både belasta uttaget och skapa värme kring adaptrar. Följ varje produkts anvisningar, använd inte flera grendosor efter varandra och skapa inte en permanent lösning där fasta uttag behövs."], },
      { heading: "Agera vid varningssignaler", paragraphs: ["Lukt av bränt, missfärgning, varm plast, glapp eller ljud från en kontakt är skäl att genast sluta använda den berörda utrustningen. Om problemet verkar sitta i vägguttaget eller den fasta installationen ska en registrerad elinstallatör kontaktas."], },
    ],
    sourceLabel: "Elsäkerhetsverket: Kontrollera dina elprodukter",
    sourceUrl: "https://www.elsakerhetsverket.se/privatpersoner/dina-elprodukter/kontrollera-dina-elprodukter/",
  }),
  guide({
    slug: "gamla-elprodukter-nar-ska-de-byta",
    title: "Gamla elprodukter hemma – när är det dags att ta dem ur bruk?",
    description: "Äldre lampor, laddare och apparater kan vara säkra – men slitage och skador ska alltid tas på allvar.",
    category: "Elprodukter",
    readTime: "5 min läsning",
    accent: "green",
    intro: "Ålder i sig avgör inte om en elprodukt är farlig, men äldre produkter kan ha slitage och sakna den konstruktion eller märkning som nyare produkter har. Det viktiga är produktens skick, hur den används och om du kan bedöma att den fortfarande är säker.",
    safetyNote: "Fortsätt aldrig använda en gammal produkt som glappar, blir ovanligt varm, luktar bränt eller har skadad sladd, stickpropp eller isolering.",
    sections: [
      { heading: "Börja med synliga delar", paragraphs: ["Kontrollera att sladden sitter ordentligt fast i både produkt och stickpropp och att isoleringen är hel. Leta efter sprickor, missfärgning, klämskador och trasiga höljen. Äldre produkter behöver ofta granskas extra noga eftersom vanligt slitage kan ha byggts upp över tid."], },
      { heading: "Lyssna och lukta efter förändringar", paragraphs: ["Konstiga ljud, bränd lukt, glapp och säkringar som löser ut är tecken på elektriskt fel enligt Elsäkerhetsverket. Sluta då använda produkten direkt. Det räcker inte att felet försvinner när du rör kabeln eller byter uttag."], steps: ["Dra ur stickproppen om det kan göras säkert.", "Märk eller lägg undan produkten så att den inte används av misstag.", "Låt en fackperson bedöma reparation eller ersätt produkten."] },
      { heading: "Kontrollera rätt användning", paragraphs: ["Använd bara produkten i den miljö den är avsedd för. En gammal inomhusprodukt ska inte flyttas ut på balkong eller i förråd bara för att den fortfarande fungerar. Saknas anvisning kan tillverkaren eller säljaren ibland hjälpa dig att hitta rätt information."], },
      { heading: "Återvinn hellre än att chansa", paragraphs: ["En produkt som inte kan bedömas som säker ska inte sparas som reserv eller säljas vidare. Lämna den som elavfall enligt kommunens anvisningar. Att ta en osäker produkt ur bruk är ett säkrare val än att försöka få den att fungera en säsong till."], },
    ],
    sourceLabel: "Elsäkerhetsverket: Produkter A–Ö",
    sourceUrl: "https://www.elsakerhetsverket.se/privatpersoner/dina-elprodukter/produkter/",
  }),
  guide({
    slug: "hyra-ut-bostad-elansvar",
    title: "Hyra ut bostad – du har fortfarande ansvar för elsäkerheten",
    description: "Ska du hyra ut hus eller lägenhet? Så tydliggör du elansvar, kontroller och felanmälan före inflyttning.",
    category: "Elsäkerhet hemma",
    readTime: "5 min läsning",
    accent: "blue",
    intro: "När du hyr ut en bostad är du fortfarande innehavare av elanläggningen och ansvarar för att den är säker. Ett bra avtal och en enkel kontroll före inflyttning minskar risken för missförstånd och hjälper fel att komma fram tidigt.",
    safetyNote: "Lämna inte kvar skadade apparater, lösa uttag eller kända elfel i en uthyrd bostad. Brister ska åtgärdas, inte skrivas bort i avtalet.",
    sections: [
      { heading: "Ansvaret följer inte med hyresgästen", paragraphs: ["Elsäkerhetsverket anger att ägaren som hyr ut en bostad fortfarande är innehavare av elanläggningen och ansvarig för dess säkerhet. Du behöver dessutom kunna få tillgång till anläggningen för att fortlöpande kunna kontrollera säkerheten."], },
      { heading: "Skriv hur fel ska hanteras", paragraphs: ["Avtalet bör tydligt beskriva hur hyresgästen anmäler fel och vem som ansvarar för de elprodukter som lämnas kvar i bostaden. Uppmana hyresgästen att sluta använda sådant som blir varmt, glappar, luktar bränt eller ser skadat ut."], steps: ["Gå igenom synliga uttag, brytare och elprodukter före inflyttning.", "Spara uppgifter om elcentral, jordfelsbrytare och kontaktväg vid fel.", "Dokumentera kända åtgärder och lämna relevanta anvisningar."] },
      { heading: "Kontrollera före och under uthyrningen", paragraphs: ["Gör en rimlig fortlöpande kontroll utifrån bostadens ålder, miljö och användning. Var särskilt uppmärksam på skador efter renovering, fuktproblem, överbelastade uttag och apparater som står kvar i bostaden."], },
      { heading: "Vid tecken på akut fara", paragraphs: ["Hyresgästen ska veta att rök, brand, skadade kablar eller misstänkt elchock behöver hanteras skyndsamt. Vid akut fara gäller 112. I mindre akuta fall ska den berörda delen sluta användas tills felet har bedömts och åtgärdats."], },
    ],
    sourceLabel: "Elsäkerhetsverket: Hyra ut, sälja eller riva",
    sourceUrl: "https://www.elsakerhetsverket.se/privatpersoner/din-elanlaggning/hyra-ut-salja-eller-riva/",
  }),
  guide({
    slug: "salja-begagnad-elprodukt-privat",
    title: "Sälja begagnad elprodukt privat – kontrollera detta före annonsen",
    description: "En checklista för dig som ska sälja en begagnad lampa, laddare eller apparat utan att föra vidare en säkerhetsrisk.",
    category: "Elprodukter",
    readTime: "5 min läsning",
    accent: "green",
    intro: "En begagnad elprodukt kan få ett långt liv, men den ska vara säker för nästa användare. Innan du lägger ut en lampa, köksapparat, laddare eller annan elprodukt till försäljning behöver du granska skick, funktion och historik – och avstå om du är osäker.",
    safetyNote: "Sälj inte en trasig eller osäker elprodukt som fungerande. Modifiera inte produktens stickpropp eller skyddsklass för att göra den mer lättsåld.",
    sections: [
      { heading: "Granska sladd, kontakt och hölje", paragraphs: ["Kontrollera att kabeln och produktens utsida är hela. Stickproppens stift ska inte vara sneda eller kunna vicka, och laddare eller transformator ska vara original eller ha motsvarande tekniska prestanda. Produkten ska vara avsedd för svenska uttag och elnät."], },
      { heading: "Testa försiktigt före försäljning", paragraphs: ["Det är klokt att kontrollera att produkten fungerar och inte visar tecken på överhettning, konstig lukt eller ovanliga ljud. Testa bara om det kan göras säkert. Elsäkerhetsverket rekommenderar uttag med jordfelsbrytare eller en portabel jordfelsbrytare som extra skydd vid test."], steps: ["Kontrollera produktens märkning och synliga skick.", "Testa funktion utan att lämna produkten utan uppsikt.", "Avstå från försäljning om något glappar, luktar eller blir onormalt varmt."] },
      { heading: "Var tydlig med produktens historik", paragraphs: ["Berätta om ålder, reparationer och kända brister. En produkt som behöver repareras innan användning ska beskrivas tydligt som sådan. Det är bättre att lämna tveksam elektronik till återvinning än att låta köparen ta över en okänd risk."], },
      { heading: "Ändra inte stickpropp eller skyddsklass", paragraphs: ["När en produkt modifieras kan den ursprungliga CE-märkningen sluta gälla och ansvaret för säkerheten flyttas över till den som gjorde ändringen. Byt därför inte en ojordad stickpropp till jordad eller platt modell utan att veta vilka produktkrav som gäller."], },
    ],
    sourceLabel: "Elsäkerhetsverket: Sälja begagnade elprodukter",
    sourceUrl: "https://www.elsakerhetsverket.se/yrkespersoner/tillverka-och-salja-elprodukter/salja-begagnade-elprodukter/",
  }),
  guide({
    slug: "anvanda-utlandsk-elprodukt-i-sverige",
    title: "Använda utländsk elprodukt i Sverige – kontrollera spänning och stickpropp först",
    description: "Köpt en apparat utomlands? Här är kontrollerna som avgör om den är avsedd för svenska uttag och 230 volt.",
    category: "Elprodukter",
    readTime: "5 min läsning",
    accent: "amber",
    intro: "En produkt som fungerar i ett annat land är inte automatiskt säker att använda i Sverige. Innan du ansluter en utländsk apparat behöver du kontrollera dess märkdata, stickpropp och anvisningar. En enkel adapter kan inte göra en produkt avsedd för fel elnät säker.",
    safetyNote: "Använd inte en reseadapter som permanent lösning för en produkt som saknar svensk stickpropp eller inte är avsedd för 230 V och 50 Hz.",
    sections: [
      { heading: "Läs produktens märkdata", paragraphs: ["Kontrollera vilken spänning och frekvens produkten är avsedd för. Elsäkerhetsverket anger att elprodukter för Sverige ska vara avsedda för 230 volt och ha en stickpropp som passar svenska eluttag. Läs märkningen på både apparaten och eventuell nätadapter."], },
      { heading: "En adapter löser inte alla skillnader", paragraphs: ["En reseadapter kan ändra kontaktens form, men den ändrar inte nödvändigtvis produktens elektriska förutsättningar. Det är inte tillåtet att permanent använda en reseadapter för att ansluta en produkt som saknar rätt typ av stickpropp."], steps: ["Kontrollera spänning, frekvens och effekt på märkningen.", "Säkerställ att stickproppen är avsedd för svenska uttag.", "Avstå om dokumentation, märkning eller ansvarig tillverkare saknas."] },
      { heading: "Kontrollera information och ansvarig aktör", paragraphs: ["Det ska finnas tydlig produktidentifiering, kontaktuppgifter till tillverkare och vid behov importör inom EU/EES. Bruksanvisning och säkerhetsinformation ska finnas på svenska. Saknas uppgifter är det en anledning att inte använda produkten."], },
      { heading: "Ta inga genvägar med fast el", paragraphs: ["Klipp aldrig av en stickpropp för att få en produkt att passa och öppna inte uttag eller dosor för att göra en egen anslutning. Om produkten är fast ansluten eller om du är minsta osäker ska du avstå och rådfråga ett registrerat elinstallationsföretag."], },
    ],
    sourceLabel: "Elsäkerhetsverket: Köpa elprodukter i butik",
    sourceUrl: "https://www.elsakerhetsverket.se/privatpersoner/dina-elprodukter/kopa-elprodukter/kopa-elprodukter-i-butik/",
  }),
  guide({
    slug: "anmala-brister-i-elanlaggning",
    title: "Anmäla brister i en elanläggning – när och hur gör man?",
    description: "Så agerar du om en innehavare inte åtgärdar en misstänkt elbrist, från första kontakt till anmälan.",
    category: "Elsäkerhet hemma",
    readTime: "5 min läsning",
    accent: "red",
    intro: "Ser du en allvarlig eller återkommande brist i en elanläggning ska den som ansvarar för anläggningen först få möjlighet att åtgärda den. Om det inte sker kan du anmäla bristen till Elsäkerhetsverket. Vid omedelbar personfara eller en pågående olycka är det i stället 112 som gäller.",
    safetyNote: "Försök inte undersöka en misstänkt brist genom att öppna uttag, centraler eller kapslingar. Håll avstånd vid rök, gnistor eller skadade kablar.",
    sections: [
      { heading: "Börja med innehavaren", paragraphs: ["Elsäkerhetsverket rekommenderar att du först kontaktar innehavaren av den berörda elanläggningen, så att bristen kan uppdagas och åtgärdas. Det kan exempelvis vara fastighetsägaren, bostadsrättsföreningen eller den som äger anläggningen."], },
      { heading: "Dokumentera utan att utsätta dig", paragraphs: ["Notera plats, datum, vad du har sett och om felet återkommer. Bilder kan vara ett bra underlag om de kan tas säkert, men närbilder på skadad eller strömförande utrustning är aldrig viktigare än att hålla avstånd."], steps: ["Beskriv bristen skriftligt för innehavaren.", "Spara svar och uppgifter om vilka åtgärder som utlovats.", "Anmäl till Elsäkerhetsverket om nödvändiga åtgärder uteblir."] },
      { heading: "Så fungerar en anmälan", paragraphs: ["Elsäkerhetsverket har en e-tjänst för anmälan av brister i elanläggningar. En anmälan kan lämnas anonymt, men myndigheten har större möjlighet att följa upp om den kan kontakta dig för mer information. Anmälan blir en allmän handling."], },
      { heading: "När situationen är akut", paragraphs: ["Vid omedelbar personfara, en redan inträffad elolycka eller pågående brottslig handling ska du ringa 112. Elsäkerhetsverket upplyser också om att myndigheten inte har befogenhet att utöva tillsyn i bostäder, vilket gör den snabba kontakten med ansvarig innehavare extra viktig."], },
    ],
    sourceLabel: "Elsäkerhetsverket: Anmäl brister i en elanläggning",
    sourceUrl: "https://www.elsakerhetsverket.se/kontakta-oss/gor-en-anmalan/anmal-brister-i-elanlaggning/",
  }),
];
