import type { GuidePost } from "./posts";

export const augustGuidePosts: GuidePost[] = [
  {
    slug: "luftavfuktare-i-kallare-elrisk",
    title: "Luftavfuktare i källare – använd den säkert nära fukt",
    description: "Så placerar och kontrollerar du en luftavfuktare i källare utan att skapa risk med fukt, sladdar och uttag.",
    category: "Källare",
    readTime: "4 min läsning",
    publishedAt: "2026-08-22",
    updatedLabel: "Uppdaterad 22 augusti 2026",
    accent: "blue",
    intro: "En luftavfuktare kan vara praktisk i en fuktig källare, men den används ofta länge och nära vatten, golvbrunnar eller kalla väggar. Därför behöver både produkt, uttag och placering kontrolleras innan den lämnas i drift.",
    safetyNote: "Använd inte en avfuktare med skadad sladd, fukt i stickproppen eller ovanlig värme. Stäng av och dra ur kontakten om det kan göras säkert.",
    sections: [
      { heading: "Placera den torrt och stabilt", paragraphs: ["Ställ avfuktaren enligt bruksanvisningen, med fri luft runt produkten och utan att sladden ligger i vatten eller pressas mot vassa kanter. Undvik förlängningssladd om det går, särskilt i en miljö där golvet kan bli fuktigt."], steps: ["Kontrollera att uttag och stickpropp är torra.", "Håll sladd och kopplingar från golvbrunnar och vatten.", "Töm behållare och rengör filter enligt bruksanvisningen."] },
      { heading: "Kontrollera drift över tid", paragraphs: ["Eftersom avfuktare ofta går många timmar i följd bör du kontrollera att produkten inte låter annorlunda, luktar bränt eller blir onormalt varm. Kontrollera också att slangen för kondensvatten inte kan läcka mot eluttag, grenuttag eller kabelskarvar."] },
      { heading: "Tänk på källarens elanläggning", paragraphs: ["Fukt, äldre uttag och otydliga grupper kan göra felsökning svårare. Om jordfelsbrytaren löser ut när avfuktaren används ska du inte fortsätta återställa skyddet gång på gång. Låt produkten vara urkopplad tills orsaken är utredd."] },
      { heading: "När behöver du elektriker?", paragraphs: ["Kontakta ett registrerat elinstallationsföretag om uttaget blir varmt, sitter löst, saknar rätt skydd för miljön eller om jordfelsbrytare eller säkring löser ut återkommande. Öppna inte uttag, dosa eller elcentral själv."] },
    ],
    sourceLabel: "Elsäkerhetsverket: Kontrollera dina elprodukter",
    sourceUrl: "https://www.elsakerhetsverket.se/privatpersoner/dina-elprodukter/kontrollera-dina-elprodukter/",
  },
  {
    slug: "frostvakt-i-fritidshus-sakert",
    title: "Frostvakt i fritidshus – så undviker du brand- och elrisk",
    description: "Praktiska råd när en frostvakt eller liten värmare ska hålla stugan frostfri under kalla perioder.",
    category: "Fritidshus",
    readTime: "4 min läsning",
    publishedAt: "2026-08-22",
    updatedLabel: "Uppdaterad 22 augusti 2026",
    accent: "amber",
    intro: "En frostvakt kan skydda rör och utrymmen i ett fritidshus, men den är samtidigt en värmeprodukt som kan stå på under lång tid utan daglig uppsikt. Säkerheten avgörs av produktens skick, placering och bostadens elanläggning.",
    safetyNote: "Täck aldrig över en frostvakt och placera den inte nära textilier, kartonger, träpanel eller annat brännbart material.",
    sections: [
      { heading: "Välj en produkt för uppgiften", paragraphs: ["Använd en frostvakt eller värmare som är avsedd för den miljö där den ska stå. Följ tillverkarens krav på fri yta, montering och temperatur. En vanlig portabel värmefläkt är sällan ett bra val för lång obevakad drift."] },
      { heading: "Kontrollera platsen innan du lämnar", paragraphs: ["Se till att sladd, stickpropp och uttag är hela och att produkten står stabilt. Ta bort brännbart material runt värmaren och kontrollera att gardiner, förvaring eller möbler inte kan glida eller blåsa mot den."], steps: ["Läs produktens anvisning om minsta avstånd.", "Kontrollera sladd och uttag efter skador.", "Fotografera gärna inställning och placering innan du lämnar huset."] },
      { heading: "Undvik provisoriska lösningar", paragraphs: ["Koppla inte frostvakten via hopkedjade grenuttag eller gamla förlängningssladdar. Om uttag saknas på rätt plats är det bättre att låta en elektriker installera en fast och lämplig lösning än att låta en tillfällig kabel bli permanent."] },
      { heading: "När behöver du elektriker?", paragraphs: ["Ta hjälp om säkringen löser ut, om uttaget blir varmt eller om huset har äldre el där du är osäker på jordfelsbrytare och belastning. Ett fritidshus som står tomt länge förtjänar en extra noggrann kontroll."] },
    ],
    sourceLabel: "Elsäkerhetsverket: Installation av elektriska element",
    sourceUrl: "https://www.elsakerhetsverket.se/privatpersoner/din-elanlaggning/bygga-och-renovera/installation-av-elektriska-element/",
  },
  {
    slug: "ladda-verktygsbatterier-i-garage",
    title: "Ladda verktygsbatterier i garage – gör det säkert",
    description: "Så minskar du risken när batterier till skruvdragare, gräsklippare och verktyg laddas i garage eller förråd.",
    category: "Batterier",
    readTime: "4 min läsning",
    publishedAt: "2026-08-22",
    updatedLabel: "Uppdaterad 22 augusti 2026",
    accent: "green",
    intro: "Batterier till elverktyg och trädgårdsmaskiner laddas ofta i garage, förråd eller källare där damm, kyla och fukt kan påverka både laddare och uttag. En enkel laddrutin gör stor skillnad för säkerheten.",
    safetyNote: "Ladda inte ett batteri som är skadat, svullet, ovanligt varmt eller har utsatts för slag. Använd bara laddare som är avsedd för batteriet.",
    sections: [
      { heading: "Skapa en fast laddplats", paragraphs: ["Välj en torr, synlig och ventilerad plats där laddaren inte täcks av verktyg, sågspån, tyg eller kartonger. Laddplatsen ska vara lätt att kontrollera och inte blockera en utrymningsväg."] },
      { heading: "Ladda med uppsikt", paragraphs: ["Låt inte flera batterier laddas obevakat över natten. Följ tillverkarens anvisning om temperatur, laddtid och förvaring. Koppla ur laddaren när laddningen är klar och kontrollera regelbundet att kabel och nätadapter är hela."], steps: ["Använd rätt laddare för batteriet.", "Placera laddaren på obrännbart, torrt underlag.", "Koppla ur när laddningen är klar.", "Ta skadade batterier ur bruk direkt."] },
      { heading: "Garage har särskilda risker", paragraphs: ["I garage finns ofta bränsle, färg, damm och andra material som kan förvärra en brand. Håll laddplatsen ren och undvik att ladda nära lösningsmedel, textilier eller pappersförvaring."] },
      { heading: "När behöver du elektriker?", paragraphs: ["Om uttaget eller grenuttaget blir varmt, om säkringen löser ut eller om du vill bygga en permanent laddstation med flera uttag i garaget bör ett registrerat elinstallationsföretag bedöma installationen."] },
    ],
    sourceLabel: "Elsäkerhetsverket: Laddare",
    sourceUrl: "https://www.elsakerhetsverket.se/privatpersoner/dina-elprodukter/produkter/laddare/",
  },
  {
    slug: "motionsband-hemma-eluttag",
    title: "Motionsband hemma – räcker eluttaget och vad ska du kontrollera?",
    description: "En trygg checklista för löpband, crosstrainer och annan träningsutrustning med motor hemma.",
    category: "Elprodukter",
    readTime: "4 min läsning",
    publishedAt: "2026-08-22",
    updatedLabel: "Uppdaterad 22 augusti 2026",
    accent: "blue",
    intro: "Motionsband och träningsmaskiner med motor kan dra mer ström än småelektronik och används ofta nära mattor, damm och förlängningssladdar. Kontrollera därför både produktens krav och uttagets skick innan maskinen blir en del av vardagen.",
    safetyNote: "Använd inte träningsutrustning som luktar bränt, får varm stickpropp, ger stötar eller löser ut säkring eller jordfelsbrytare.",
    sections: [
      { heading: "Läs märkning och bruksanvisning", paragraphs: ["Kontrollera om produkten ska anslutas direkt i vägguttag och vilken effekt den kräver. Undvik långa förlängningssladdar och hopkopplade grenuttag, särskilt om maskinen har motor och används länge åt gången."] },
      { heading: "Placera sladden rätt", paragraphs: ["Sladden ska inte ligga under motionsbandet, klämmas av stativ eller hamna där den nöts av rörelse. Håll området rent från damm och textilier så att motor och nätadapter kan ventileras."] },
      { heading: "Var uppmärksam vid start", paragraphs: ["Om belysningen blinkar kraftigt när maskinen startar, eller om samma säkring löser ut vid användning, kan gruppen vara belastad eller installationen behöva kontrolleras. Fortsätt inte använda maskinen som om inget hänt."], steps: ["Kontrollera sladd och stickpropp före första användning.", "Anslut enligt tillverkarens anvisning.", "Avbryt vid värme, lukt, stötar eller återkommande frånslag."] },
      { heading: "När behöver du elektriker?", paragraphs: ["Kontakta elektriker om uttaget blir varmt, sitter löst eller om säkringar löser ut återkommande. Själva träningsmaskinen hanteras normalt av serviceverkstad, men den fasta elanläggningen ska bedömas av registrerat elföretag."] },
    ],
    sourceLabel: "Elsäkerhetsverket: Kontrollera dina elprodukter",
    sourceUrl: "https://www.elsakerhetsverket.se/privatpersoner/dina-elprodukter/kontrollera-dina-elprodukter/",
  },
  {
    slug: "akvarium-eluttag-pump-belysning",
    title: "Akvarium hemma – säker el till pump, värmare och belysning",
    description: "Så minskar du risken när akvariets elprodukter används nära vatten under lång tid.",
    category: "Elprodukter",
    readTime: "5 min läsning",
    publishedAt: "2026-08-22",
    updatedLabel: "Uppdaterad 22 augusti 2026",
    accent: "green",
    intro: "Ett akvarium samlar flera elprodukter nära vatten: pump, doppvärmare, belysning och ibland timer. Eftersom utrustningen ofta är igång dygnet runt behöver anslutningarna vara torra, hela och lätta att kontrollera.",
    safetyNote: "Dra ur kontakten innan du arbetar i eller nära akvariet. Rör inte elutrustning med våta händer.",
    sections: [
      { heading: "Håll vatten borta från kontakter", paragraphs: ["Placera grenuttag och timer så att vatten inte kan droppa ner i dem. Låt kablar ha en droppögla under uttaget, så att eventuellt vatten rinner av innan det når stickproppen. Använd bara produkter som är avsedda för akvarium och följ deras anvisningar."] },
      { heading: "Kontrollera utrustningen regelbundet", paragraphs: ["Salt, kalk och fukt kan påverka produkter över tid. Titta efter sprickor, missfärgning, glapp och värme. En doppvärmare med skadat glas eller kabel ska inte användas, även om den fortfarande verkar fungera."] },
      { heading: "Undvik överfulla grenuttag", paragraphs: ["Akvarium kräver ofta flera kontakter, men det betyder inte att flera grendosor ska kopplas efter varandra bakom möbeln. Välj en ordnad placering där varje kontakt går att se och nå vid behov."], steps: ["Skapa droppögla på varje kabel.", "Placera uttag och timer högre än risk för stänk.", "Koppla ur innan vattenbyte och service.", "Byt skadad utrustning i stället för att laga provisoriskt."] },
      { heading: "När behöver du elektriker?", paragraphs: ["Kontakta ett registrerat elinstallationsföretag om uttaget sitter löst, blir varmt eller om du vill installera fler fasta uttag på en säkrare plats. Flytta inte fasta uttag själv för att passa akvariemöbeln."] },
    ],
    sourceLabel: "Elsäkerhetsverket: Kontrollera dina elprodukter",
    sourceUrl: "https://www.elsakerhetsverket.se/privatpersoner/dina-elprodukter/kontrollera-dina-elprodukter/",
  },
  {
    slug: "torktumlare-luddfilter-brandrisk",
    title: "Torktumlarens luddfilter – därför är det en elsäkerhetsfråga",
    description: "Rengöring, ventilation och varningssignaler som minskar risken för överhettning i torktumlare.",
    category: "Vitvaror",
    readTime: "4 min läsning",
    publishedAt: "2026-08-22",
    updatedLabel: "Uppdaterad 22 augusti 2026",
    accent: "amber",
    intro: "Ludd, damm och blockerad ventilation gör att en torktumlare kan bli varmare än den ska. Eftersom tumlaren kombinerar motor, värme och lång drift är rengöring av filter och luftvägar en viktig del av säker användning.",
    safetyNote: "Använd inte torktumlaren om den luktar bränt, blir ovanligt varm, låter annorlunda eller om säkring eller jordfelsbrytare löser ut.",
    sections: [
      { heading: "Rengör efter bruksanvisningen", paragraphs: ["Töm luddfilter så ofta tillverkaren anger, ofta efter varje körning. Kontrollera även kondensor, vattenbehållare och luftvägar om modellen kräver det. En ren maskin arbetar lättare och minskar risken för onödig värmeutveckling."] },
      { heading: "Se till att maskinen kan ventilera", paragraphs: ["Torktumlaren ska stå så att luft kan cirkulera enligt anvisningen. Skjut inte in textilier, förvaring eller damm bakom maskinen på ett sätt som blockerar ventilationen eller ligger mot kabel och uttag."] },
      { heading: "Kör med uppsikt när det går", paragraphs: ["Undvik att starta torktumlaren precis innan du går hemifrån eller lägger dig, särskilt om maskinen är äldre eller nyligen har betett sig annorlunda. Elsäkerhetsverket rekommenderar att använda så få elprodukter som möjligt när du sover eller är borta."], steps: ["Töm luddfilter regelbundet.", "Kontrollera att ventilationen inte är blockerad.", "Avbryt vid lukt, värme eller avvikande ljud.", "Låt fel bedömas innan maskinen används igen."] },
      { heading: "När behöver du elektriker?", paragraphs: ["Om problemet verkar sitta i uttaget, den fasta anslutningen eller återkommande frånslag i elcentralen ska ett registrerat elinstallationsföretag kontaktas. Produktfel hanteras normalt av vitvaruservice."] },
    ],
    sourceLabel: "Elsäkerhetsverket: Använda disk- och tvättmaskin nattetid",
    sourceUrl: "https://www.elsakerhetsverket.se/privatpersoner/dina-elprodukter/anvanda-elprodukter/anvanda-disk-och-tvattmaskin-nattetid/",
  },
  {
    slug: "portabelt-element-med-stickpropp",
    title: "Portabelt element med stickpropp – använd det utan att överbelasta",
    description: "Så placerar du ett flyttbart element säkert och känner igen när uttag, sladd eller säkring säger ifrån.",
    category: "Uppvärmning",
    readTime: "4 min läsning",
    publishedAt: "2026-08-22",
    updatedLabel: "Uppdaterad 22 augusti 2026",
    accent: "red",
    intro: "Ett portabelt element kan snabbt ge extra värme, men det är också en effektkrävande elprodukt. Fel placering, täckta luftöppningar eller olämpliga förlängningssladdar kan skapa överhettning och brandrisk.",
    safetyNote: "Täck aldrig över ett portabelt element och använd det inte för att torka kläder, skor eller textilier.",
    sections: [
      { heading: "Anslut helst direkt i vägguttag", paragraphs: ["Ett flyttbart element bör normalt anslutas direkt i ett helt vägguttag. Undvik grenuttag och förlängningssladdar om tillverkaren inte uttryckligen tillåter det, eftersom kontaktpunkterna kan bli varma vid hög belastning."] },
      { heading: "Håll fri yta runt värmen", paragraphs: ["Följ produktens anvisning om avstånd till möbler, gardiner och väggar. Placera elementet stabilt där det inte riskerar att välta eller blockeras av barn, husdjur, tvättställning eller förvaring."] },
      { heading: "Se upp med återkommande frånslag", paragraphs: ["Om säkringen löser ut när elementet används tillsammans med andra produkter kan gruppen vara överbelastad. Byt inte till större säkring och fortsätt inte starta om utan att minska belastningen eller ta hjälp."] , steps: ["Anslut i helt vägguttag.", "Håll avstånd till textilier och möbler.", "Avbryt vid varm stickpropp, lukt eller frånslag.", "Förvara elementet torrt när det inte används."] },
      { heading: "När behöver du elektriker?", paragraphs: ["Kontakta elektriker om uttaget blir varmt, är missfärgat eller om samma säkring löser ut återkommande. Vill du ha permanent elvärme är ett fast anslutet element ett elinstallationsarbete för registrerat elföretag."] },
    ],
    sourceLabel: "Elsäkerhetsverket: Installation av elektriska element",
    sourceUrl: "https://www.elsakerhetsverket.se/privatpersoner/din-elanlaggning/bygga-och-renovera/installation-av-elektriska-element/",
  },
  {
    slug: "ups-batteribackup-hemma",
    title: "UPS och batteribackup hemma – säker drift för dator och nätverk",
    description: "Vad du bör kontrollera innan du använder en UPS till router, dator eller hemmakontor vid strömavbrott.",
    category: "Hemmakontor",
    readTime: "4 min läsning",
    publishedAt: "2026-08-22",
    updatedLabel: "Uppdaterad 22 augusti 2026",
    accent: "blue",
    intro: "En UPS kan hålla router, dator eller nätverksutrustning igång vid korta strömavbrott. Samtidigt innehåller den batterier och elektronik som behöver placeras rätt, ventileras och kontrolleras över tid.",
    safetyNote: "Använd inte en UPS som är svullen, luktar bränt, piper onormalt eller blir varm trots låg belastning. Koppla ur den om det kan göras säkert.",
    sections: [
      { heading: "Dimensionera för rätt utrustning", paragraphs: ["Anslut bara den typ och mängd utrustning som UPS:en är avsedd för. Koppla inte in element, kaffebryggare, skrivare med hög effekt eller annan utrustning som tillverkaren avråder från."] },
      { heading: "Placera med luft runt batteriet", paragraphs: ["UPS:en ska stå torrt, stabilt och med ventilation runt höljet. Undvik stängda skåp, textilier och dammiga kabelhörn. Kontrollera också att batteriet har ett rekommenderat bytesintervall och följ tillverkarens anvisning."] },
      { heading: "Testa innan avbrottet", paragraphs: ["Prova funktionen enligt bruksanvisningen medan du är hemma och kan övervaka utrustningen. Kontrollera att larm, display eller app visar normal status och att anslutna produkter startar som förväntat efter ett avbrott."] , steps: ["Läs maxbelastning och avsedda användningsområden.", "Placera UPS:en torrt och ventilerat.", "Kontrollera batteristatus regelbundet.", "Kassera batterier enligt anvisning om de är skadade."] },
      { heading: "När behöver du elektriker?", paragraphs: ["En lös UPS kräver normalt inte elektriker, men återkommande frånslag, varma uttag eller behov av fler fasta uttag för hemmakontor ska bedömas av registrerat elinstallationsföretag."] },
    ],
    sourceLabel: "Elsäkerhetsverket: Laddare",
    sourceUrl: "https://www.elsakerhetsverket.se/privatpersoner/dina-elprodukter/produkter/laddare/",
  },
  {
    slug: "festbelysning-ljudanlaggning-hemma",
    title: "Festbelysning och ljudanläggning hemma – undvik överbelastning",
    description: "Säkra råd när lampor, högtalare, rökmaskin och laddare ska användas samtidigt hemma.",
    category: "Belysning",
    readTime: "4 min läsning",
    publishedAt: "2026-08-22",
    updatedLabel: "Uppdaterad 22 augusti 2026",
    accent: "amber",
    intro: "Tillfällig festutrustning kan snabbt fylla ett rum med grenuttag, kablar och varma adaptrar. Planera anslutningen innan gästerna kommer, så att belysning och ljud inte blir en risk när rummet är fullt och uppsikten sämre.",
    safetyNote: "Koppla inte flera grenuttag efter varandra och dra inte kablar under mattor eller genom dörröppningar där de kan klämmas.",
    sections: [
      { heading: "Samla inte allt på ett uttag", paragraphs: ["Flera lampor, högtalare, laddare och effekter kan tillsammans belasta ett uttag mer än du tänker på. Läs märkningen, använd hela produkter och fördela belastningen på ett genomtänkt sätt utan hopkedjade grenuttag."] },
      { heading: "Skydda kablar från folk och möbler", paragraphs: ["Kablar som ligger över golv kan bli snubbelrisk och samtidigt skadas av stolar, bord och dörrar. Tejp kan minska snubbelrisk men lagar aldrig en skadad kabel. Placera utrustning så att kontakter går att nå om något behöver brytas snabbt."] },
      { heading: "Se upp med värme och textilier", paragraphs: ["Lampor, nätadaptrar och vissa effekter kan bli varma. Håll dem från gardiner, pynt, dukar och soffor. Lämna inte utrustningen på efter festen när rummet töms och ingen längre märker lukt, värme eller ljud."] , steps: ["Kontrollera all utrustning före inkoppling.", "Undvik hopkedjade grenuttag.", "Håll kontakter synliga och åtkomliga.", "Stäng av och koppla ur när festen är slut."] },
      { heading: "När behöver du elektriker?", paragraphs: ["Om säkringen löser ut, uttag blir varma eller du ofta arrangerar evenemang hemma kan ett registrerat elinstallationsföretag bedöma om fler fasta uttag eller annan gruppindelning behövs."] },
    ],
    sourceLabel: "Elsäkerhetsverket: Belysning",
    sourceUrl: "https://www.elsakerhetsverket.se/privatpersoner/dina-elprodukter/produkter/belysning/",
  },
  {
    slug: "vattenkokare-och-kaffebryggare-samma-uttag",
    title: "Vattenkokare och kaffebryggare i samma uttag – är det säkert?",
    description: "Så tänker du kring köksapparater med hög effekt, grenuttag och säkringar som löser ut.",
    category: "Kök",
    readTime: "4 min läsning",
    publishedAt: "2026-08-22",
    updatedLabel: "Uppdaterad 22 augusti 2026",
    accent: "red",
    intro: "Vattenkokare, kaffebryggare och brödrost används ofta på samma bänkyta. De kan dra hög effekt var för sig, och om flera används samtidigt via samma grenuttag kan både säkring och kontaktpunkter belastas hårt.",
    safetyNote: "Använd inte ett grenuttag i köket som blir varmt, är missfärgat eller ligger där vatten kan rinna ner i kontakterna.",
    sections: [
      { heading: "Hög effekt under kort tid räknas också", paragraphs: ["Även om vattenkokaren bara går några minuter kan effekten vara hög. Om flera köksapparater startas samtidigt på samma grupp kan säkringen lösa ut. Det är en signal att minska belastningen, inte att byta till större säkring."] },
      { heading: "Undvik grenuttag nära vatten", paragraphs: ["Köksbänken är en miljö med spill, ånga och flyttbara apparater. Anslut helst produkter direkt i fasta uttag och placera sladdar så att de inte hänger över diskho, spis eller varma ytor."] },
      { heading: "Kontrollera apparaternas skick", paragraphs: ["Sluta använda apparater med skadad sladd, sprucken kontakt, läckage, bränd lukt eller ovanligt ljud. Dra ur kontakten när apparaten inte används, särskilt för produkter med värmeelement."] , steps: ["Använd inte flera effektkrävande köksapparater samtidigt på samma grenuttag.", "Håll kontakter borta från vatten och värme.", "Avbryt vid varm stickpropp eller utlöst säkring.", "Låt fasta uttag bedömas vid återkommande problem."] },
      { heading: "När behöver du elektriker?", paragraphs: ["Kontakta ett registrerat elinstallationsföretag om köksuttag blir varma, sitter löst eller om samma säkring löser ut ofta trots att du minskat belastningen. Nya fasta uttag och ändrad gruppindelning är elinstallationsarbete."] },
    ],
    sourceLabel: "Elsäkerhetsverket: Vitvaror",
    sourceUrl: "https://www.elsakerhetsverket.se/privatpersoner/dina-elprodukter/produkter/vitvaror/",
  },
];
