import type { GuidePost } from "./posts";

export const renovationGuidePosts: GuidePost[] = [
  {
    slug: "bygga-ut-huset-planera-elen",
    publishedAt: "2026-06-09",
    updatedLabel: "Uppdaterad 9 juni 2026",
    title: "Bygga ut huset – så planerar du elen innan bygget börjar",
    description: "Planera uttag, belysning, värme och elcentral i rätt ordning när huset ska byggas ut.",
    category: "Renovering",
    readTime: "6 min läsning",
    accent: "blue",
    intro: "En tillbyggnad behöver mer än några extra uttag. När ytan, användningen och belastningen förändras kan både nya ledningar, fler grupper och en bedömning av elcentralen behövas. Ta in elfrågorna tidigt, medan väggar och tak fortfarande är öppna.",
    safetyNote: "Nya ledningar, uttag och ändringar i elcentralen är elinstallationsarbete. Anlita ett registrerat elföretag för arbetet.",
    sections: [
      { heading: "Börja med hur rummet ska användas", paragraphs: ["Gör en enkel rumslista innan ritningen låses: var ska belysning, arbetsplats, media, fönsterbelysning, värme och eventuell laddning finnas? Tänk även på möblering och framtida behov. Det minskar risken för skarvsladdar och efterarbeten när tillbyggnaden redan är klar."], steps: ["Markera fasta funktioner och önskade uttag på ritningen.", "Beskriv vilka produkter som kan användas samtidigt.", "Visa elektriker och övriga hantverkare samma underlag."] },
      { heading: "Låt elcentral och grupper bedömas tidigt", paragraphs: ["En tillbyggnad kan innebära att elanläggningen behöver utvidgas och att elcentralen byggs om eller kompletteras. Berätta därför om nya effektkrävande funktioner, till exempel elvärme, golvvärme eller framtida laddning. Elektrikern kan bedöma lösningen utifrån den befintliga anläggningen i stället för att planera efter antaganden."], },
      { heading: "Samordna före isolering och skivor", paragraphs: ["Bestäm placering av dosor, takpunkter, reglage och kabelvägar innan väggar och tak stängs. Fotografera gärna öppna väggar som komplement till den dokumentation du får från elföretaget, men ändra inte dragningarna själv. Fråga vem som ansvarar för håltagning, återställning och eventuella ändringar på plats."], },
      { heading: "Kontrollera företaget och spara underlag", paragraphs: ["Elsäkerhetsverket anger att elinstallationsarbete i bostäder ska utföras av ett företag registrerat för verksamhetstypen Bostäder. Kontrollera företaget före beställning och spara offert, gruppförteckning och information om utförda ändringar. Underlaget hjälper både vid framtida renovering och felsökning."], },
    ],
    sourceLabel: "Elsäkerhetsverket: Bygga och renovera",
    sourceUrl: "https://www.elsakerhetsverket.se/privatpersoner/din-elanlaggning/bygga-och-renovera/",
  },
  {
    slug: "el-till-attefallshus-och-friggebod",
    publishedAt: "2026-06-10",
    updatedLabel: "Uppdaterad 10 juni 2026",
    title: "El till Attefallshus eller friggebod – planera säkert från start",
    description: "Så tar du med elen i planeringen av en friggebod eller ett Attefallshus, från behov till registrerat elföretag.",
    category: "Renovering",
    readTime: "6 min läsning",
    accent: "green",
    intro: "En friggebod eller ett Attefallshus används ofta som förråd, arbetsrum eller extra boende. Det påverkar vad elen behöver klara. Planera funktionerna innan byggnaden färdigställs så att lösningen kan dimensioneras och installeras säkert från början.",
    safetyNote: "Dra inte egen el från huset till byggnaden och använd inte skarvsladd som permanent lösning. Elinstallationsarbetet ska utföras av ett registrerat elföretag.",
    sections: [
      { heading: "Beskriv användningen, inte bara antalet uttag", paragraphs: ["Ett kallförråd med en lampa har andra behov än ett isolerat arbetsrum med dator, värme och belysning. Skriv ner vilka fasta och lösa produkter som ska användas, hur ofta och samtidigt. Då får installatören ett bättre underlag att bedöma matning, grupper, placering och möjlig framtida utbyggnad."], },
      { heading: "Planera mark och bygg samtidigt", paragraphs: ["Om elen ska mellan hus och komplementbyggnad behöver kabelväg och markarbete samordnas med grunden, dränering och övriga ledningar. Kontrollera också om andra kablar finns i marken innan grävning. Att en kabel behöver fram betyder inte att du själv får förlägga eller ansluta den."], },
      { heading: "Undvik provisorier som blir kvar", paragraphs: ["En skarvsladd genom dörr, fönster eller över tomten är inte en varaktig installation. Den kan skadas av klämning, fukt, trädgårdsarbete och kyla. Om byggnaden ska användas återkommande är en planerad installation ett säkrare sätt att få ljus och el där den behövs."], steps: ["Bestäm byggnadens användning.", "Visa önskad kabelväg och funktioner för elföretaget.", "Samordna markarbete och installation.", "Spara dokumentationen när arbetet är klart."] },
      { heading: "Tänk på ditt ansvar efteråt", paragraphs: ["När anläggningen är klar ansvarar innehavaren för att den används på det sätt den är anpassad för och kontrolleras fortlöpande. Var uppmärksam på skador, fukt, återkommande utlösta skydd eller förändrad användning. Låt ett elföretag bedöma ändringar i stället för att bygga vidare med tillfälliga lösningar."], },
    ],
    sourceLabel: "Elsäkerhetsverket: Bygga och renovera",
    sourceUrl: "https://www.elsakerhetsverket.se/privatpersoner/din-elanlaggning/bygga-och-renovera/",
  },
  {
    slug: "dra-el-i-mark-till-forrad-eller-uthus",
    publishedAt: "2026-06-11",
    updatedLabel: "Uppdaterad 11 juni 2026",
    title: "Dra el i mark till förråd eller uthus – vad gäller?",
    description: "Markkabel till ett uthus är elinstallationsarbete. Så planerar du kabelväg och markarbete på ett säkert sätt.",
    category: "Elinstallationsregler",
    readTime: "5 min läsning",
    accent: "amber",
    intro: "El till ett förråd, växthus eller uthus behöver tåla både fukt, grävning och framtida förändringar på tomten. Det räcker inte att kabeln kommer ner i marken; förläggningen och anslutningen måste planeras och utföras rätt.",
    safetyNote: "Förläggning av kabel i mark får inte göras som ett eget hemmajobb. Ta aldrig för givet att en gammal eller synlig kabel är spänningslös.",
    sections: [
      { heading: "Markkabel är inte ett gör-det-själv-arbete", paragraphs: ["Elsäkerhetsverket anger att förläggning av kabel i mark är elinstallationsarbete och ska utföras av ett registrerat elinstallationsföretag. Det gäller även när sträckan är kort och bara ska försörja en mindre byggnad. Felaktig förläggning kan skapa risk både vid användning och nästa gång marken grävs upp."], },
      { heading: "Sök information om ledningar före grävning", paragraphs: ["Kabelvägen kan korsa eller ligga nära andra ledningar. Kontrollera därför vad som finns i marken innan arbetet påbörjas, och låt inte grävmaskin eller handverktyg användas på antaganden. Vid nybyggnad eller större arbete kan även luftledningar i närheten påverka hur arbetet måste planeras."], },
      { heading: "Samordna ansvar mellan mark och el", paragraphs: ["Bestäm i förväg vem som ansvarar för schakt, återfyllnad och förläggning av eldelen. Elföretaget behöver få rätt förutsättningar för sin del av arbetet och kan ange vilken information som behövs. Ändra inte kabelväg, djup eller material på egen hand efter att lösningen har planerats."], steps: ["Beskriv vad byggnaden ska användas till.", "Kontrollera ledningar innan marken öppnas.", "Låt elföretaget planera och utföra elinstallationen.", "Dokumentera kabelvägen för framtida arbeten."] },
      { heading: "Håll dokumentationen tillgänglig", paragraphs: ["Spara uppgifter om kabelväg, installation och vilket företag som utförde arbetet. Berätta var kabeln ligger när någon senare ska plantera, dränera eller bygga om. En förteckning och tydliga bilder kan förebygga att en dold kabel skadas år senare."], },
    ],
    sourceLabel: "Elsäkerhetsverket: Vad får jag göra själv med el?",
    sourceUrl: "https://www.elsakerhetsverket.se/privatpersoner/detta-far-du-gora-sjalv-med-el/vad-far-jag-gora-sjalv-med-el/",
  },
  {
    slug: "renovera-aldre-elinstallation-nya-regler",
    publishedAt: "2026-06-12",
    updatedLabel: "Uppdaterad 12 juni 2026",
    title: "Renovera äldre elinstallation – när gäller dagens regler?",
    description: "Förstå skillnaden mellan att behålla en äldre elanläggning och att bygga om eller utvidga den vid renovering.",
    category: "Elinstallationsregler",
    readTime: "6 min läsning",
    accent: "blue",
    intro: "En äldre elanläggning behöver inte automatiskt göras om bara för att kraven har ändrats sedan huset byggdes. Men vid renovering kan gränsen mellan befintligt och nytt få stor betydelse. Därför är det klokt att låta en fackperson bedöma anläggningen innan byggarbetet startar.",
    safetyNote: "Utgå inte från att gammal el är säker för en ny användning. Om installationen byggs om, utvidgas eller får förändrade förutsättningar ska arbetet bedömas och utföras professionellt.",
    sections: [
      { heading: "Befintligt betyder inte automatiskt fel", paragraphs: ["Huvudregeln är att en befintlig elanläggning får vara utförd enligt de regler som gällde när den togs i bruk, så länge den är i gott skick och används under säkra förhållanden. Det är alltså inte byggåret ensamt som avgör vad du behöver göra. Skador, slitage och ändrad användning behöver ändå tas på allvar."], },
      { heading: "Ombyggnad och utvidgning är något annat", paragraphs: ["När en gammal anläggning byggs om eller utvidgas ska den nya delen följa aktuella krav. Detsamma kan gälla om användningen eller miljön förändras på ett sätt som har väsentlig betydelse för elsäkerheten. Ett rum som får ny funktion, fler uttag eller ny fast utrustning bör därför tas med i planeringen från början."], },
      { heading: "Låt renoveringen bli en kontrollpunkt", paragraphs: ["När väggar öppnas och flera yrkesgrupper ändå är på plats är det ett bra tillfälle att låta ett registrerat elföretag bedöma hela eller relevanta delar av anläggningen. Be om en tydlig genomgång av vad som är befintligt, vad som ska ändras och vilken dokumentation som lämnas efteråt."], steps: ["Samla det du vet om tidigare elarbeten.", "Beskriv hur rummen ska användas efter renoveringen.", "Låt elföretaget bedöma befintligt och nytt.", "Spara information om utförda ändringar."] },
      { heading: "Var uppmärksam på varningssignaler", paragraphs: ["Bränd lukt, värme, sprickor, lösa uttag, missfärgning och återkommande säkringar är inte normala följder av ett gammalt hus. Sluta använda den berörda delen och ta hjälp. Vänta inte med att åtgärda en säkerhetsbrist bara för att en försäljnings- eller renoveringsfråga ännu inte är löst."], },
    ],
    sourceLabel: "Elsäkerhetsverket: Bygga och renovera",
    sourceUrl: "https://www.elsakerhetsverket.se/privatpersoner/din-elanlaggning/bygga-och-renovera/",
  },
  {
    slug: "flytta-eluttag-vid-renovering",
    publishedAt: "2026-06-13",
    updatedLabel: "Uppdaterad 13 juni 2026",
    title: "Flytta eluttag vid renovering – därför behövs elektriker",
    description: "Ett nytt läge för uttag ändrar den fasta installationen. Så planerar du placeringen innan väggar och skåp monteras.",
    category: "Elinstallationsregler",
    readTime: "5 min läsning",
    accent: "amber",
    intro: "När en vägg byggs om hamnar befintliga uttag ofta fel i förhållande till möbler, kök eller arbetsplats. Att flytta ett uttag är inte samma sak som att byta ett befintligt uttag i samma dosa. Det innebär en förändring av den fasta elanläggningen.",
    safetyNote: "Ta inte loss ett uttag för att förlänga ledare, flytta dosa eller dra ny kabel. Förändringar i fast installation ska utföras av ett registrerat elföretag.",
    sections: [
      { heading: "Skilj på byte och flytt", paragraphs: ["Vissa får, med rätt kunskap, byta ett befintligt uttag under särskilda förutsättningar. Men att flytta uttaget, sätta upp ett nytt eller ändra ledningsdragningen är elinstallationsarbete. Samma gräns gäller även om arbetet verkar litet och väggen redan är öppen."], },
      { heading: "Planera från möblering och funktion", paragraphs: ["Markera var säng, soffa, arbetsplats, köksutrustning och media ska stå innan elarbetet beställs. Fundera på var sladdar annars kan hamna i kläm eller behöva dras över golv. Ett bra underlag hjälper elektrikern att föreslå en säker och praktisk placering i stället för att lösa behovet med många grenuttag."], },
      { heading: "Samordna med väggens övriga arbete", paragraphs: ["Dosor, ledningar, isolering, reglar och skivor behöver samspela. Berätta för hantverkarna vilka elpunkter som ska finnas och ändra inte lägen efter att eldragningen har påbörjats utan att stämma av med elföretaget. Dokumentation eller bilder på väggen innan den stängs är värdefulla för framtida arbeten."], steps: ["Gör en möbleringsskiss.", "Markera önskade uttag och funktioner.", "Låt registrerat elföretag planera ändringen.", "Spara dokumentation om nya elpunkter."] },
      { heading: "Använd aldrig en skadad eller lös installation", paragraphs: ["Om ett befintligt uttag är löst, varmt, missfärgat eller luktar bränt ska det inte användas i väntan på renoveringen. Felanmäl eller kontakta elektriker direkt. Tejp och provisoriska täckningar är inte ett säkert sätt att hantera en skadad fast installation."], },
    ],
    sourceLabel: "Elsäkerhetsverket: Vad får jag göra själv med el?",
    sourceUrl: "https://www.elsakerhetsverket.se/privatpersoner/detta-far-du-gora-sjalv-med-el/vad-far-jag-gora-sjalv-med-el/",
  },
  {
    slug: "riva-vagg-och-dolda-elledningar",
    publishedAt: "2026-06-14",
    updatedLabel: "Uppdaterad 14 juni 2026",
    title: "Riva vägg vid renovering – planera för dolda elledningar",
    description: "Så minskar du risken att skada el när en innervägg ska rivas, flyttas eller öppnas under renoveringen.",
    category: "Renovering",
    readTime: "5 min läsning",
    accent: "red",
    intro: "En innervägg kan innehålla dosor, kablar, uttag och anslutningar även när bara en strömbrytare syns på ytan. Vid rivning är målet inte att själv kartlägga eller koppla om elen, utan att få rätt underlag och låta säkra personer hantera de delar som berörs.",
    safetyNote: "Börja inte riva, såga eller skruva i en vägg nära elpunkter på antaganden. Om en kabel eller dosa kan beröras ska elen hanteras av ett registrerat elföretag.",
    sections: [
      { heading: "Inventera synliga elpunkter före rivning", paragraphs: ["Notera uttag, strömbrytare, lamputtag, fast belysning och elcentralens gruppförteckning. Ta bilder på väggens yta och samla ritningar från tidigare arbeten om de finns. Det är användbar information för elektrikern, men ett avsaknat uttag betyder inte att väggen är fri från dolda ledningar."], },
      { heading: "Planera vad som ska hända med funktionerna", paragraphs: ["När en vägg försvinner behöver uttag, belysning och brytare ofta få ny placering eller kopplas om. Bestäm den framtida möbleringen och belysningsstyrningen före rivningen. Då kan elektriker och byggare samordna arbetet och undvika att en provisorisk lösning blir kvar bakom nya skivor."], },
      { heading: "Stanna vid oväntade fynd", paragraphs: ["Avbryt arbetet om du hittar en kabel, dosa, skadad isolering eller något som inte stämmer med underlaget. Dra inte i kabeln och försök inte flytta eller kapa den. Om någon får ström genom kroppen eller om det blir rök eller brand gäller akut hjälp först."], steps: ["Dokumentera synliga elpunkter före arbetet.", "Planera nya funktioner med elföretaget.", "Avbryt vid okända kablar eller dosor.", "Låt elen kontrolleras innan väggen byggs igen."] },
      { heading: "Spara information efteråt", paragraphs: ["Be om uppdaterad information om vad som har ändrats och var nya elpunkter finns. Den är särskilt viktig inför framtida håltagning, renovering och felsökning. En säker installation ska inte vara beroende av att nästa person gissar vad som finns bakom väggen."], },
    ],
    sourceLabel: "Elsäkerhetsverket: Bygga och renovera",
    sourceUrl: "https://www.elsakerhetsverket.se/privatpersoner/din-elanlaggning/bygga-och-renovera/",
  },
  {
    slug: "installera-fast-elelement-regler",
    publishedAt: "2026-06-15",
    updatedLabel: "Uppdaterad 15 juni 2026",
    title: "Installera fast element – regler, placering och elsäkerhet",
    description: "Ett fast anslutet element ska installeras av registrerat elföretag. Planera placering, fri yta och styrning innan köp.",
    category: "Elinstallationsregler",
    readTime: "5 min läsning",
    accent: "amber",
    intro: "När ett rum byggs om eller får ny användning kan ett fast element kännas som en enkel lösning. Men både installation och byte av ett fast anslutet elektriskt element är elinstallationsarbete. Ta ställning till placering och användning innan produkten köps in.",
    safetyNote: "Anslut eller byt inte ett fast element själv. Håll textilier, möbler och annat brännbart på avstånd enligt produktens anvisningar.",
    sections: [
      { heading: "Fast anslutning kräver rätt företag", paragraphs: ["Elsäkerhetsverket är tydligt med att installation och byte av fast anslutna elektriska element ska utföras av registrerade elföretag. Att elementet ser ut att ha en enkel kabel eller termostat förändrar inte gränsen. Elektrikern behöver bedöma hur elementet ska anslutas och vilken belastning installationen ska klara."], },
      { heading: "Välj plats utifrån både värme och säkerhet", paragraphs: ["Placeringen ska fungera med rummets möblering, fönster, gardiner och framtida användning. Ett element behöver fritt utrymme runt sig för att minska brandrisken. Följ produktens anvisningar och planera så att ingen i vardagen behöver ställa möbler eller förvara textilier direkt emot värmekällan."], },
      { heading: "Tänk igenom styrning och effektbehov", paragraphs: ["Beskriv för installatören om elementet ska styras med termostat, timer eller annan fast styrning och om flera värmekällor används i samma rum. Den typen av planering ska göras före inköp och väggmontering, inte efter att installationen har låsts av byggskivor eller inredning."], steps: ["Bestäm rummets användning och möblering.", "Kontrollera produktens anvisningar om fri yta.", "Låt registrerat elföretag bedöma anslutning och belastning.", "Använd inte elementet om det luktar bränt eller beter sig onormalt."] },
      { heading: "Skilj på produktfel och installationsfel", paragraphs: ["Om ett element blir onormalt varmt, luktar bränt, ger stötar eller får skydd att lösa ut ska det tas ur bruk och bedömas. Öppna inte hölje eller termostat. Service kan behövas för produkten, medan en registrerad installatör behöver undersöka anslutningen och den fasta elanläggningen."], },
    ],
    sourceLabel: "Elsäkerhetsverket: Installation av elektriska element",
    sourceUrl: "https://www.elsakerhetsverket.se/privatpersoner/din-elanlaggning/bygga-och-renovera/installation-av-elektriska-element/",
  },
  {
    slug: "smart-belysning-vid-renovering",
    publishedAt: "2026-06-16",
    updatedLabel: "Uppdaterad 16 juni 2026",
    title: "Smart belysning vid renovering – planera ljuset innan väggarna stängs",
    description: "Planera smart belysning med rätt gräns mellan lösa produkter och ändringar i den fasta elanläggningen.",
    category: "Smarta hem",
    readTime: "6 min läsning",
    accent: "green",
    intro: "Smarta lampor kan skapa nya rutiner och stämningar, men renoveringen är också rätt tillfälle att fundera på hur ljuset ska styras i vardagen. Skillnaden mellan en lös smart ljuskälla och en ny fast brytare eller dimmer är viktig för både planering och elsäkerhet.",
    safetyNote: "En ny eller ändrad fast brytare, dimmer eller ledningsdragning är elinstallationsarbete. Låt ett registrerat elföretag utföra den delen.",
    sections: [
      { heading: "Bestäm vilka situationer ljuset ska lösa", paragraphs: ["Gå igenom rummet vid olika tider: allmänljus, läsljus, arbetsljus, nattljus och vägen genom bostaden. Markera vilka lampor som ska kunna styras tillsammans och var vanliga fysiska reglage behövs. En tydlig funktionslista är mer användbar för planeringen än att börja med en viss app eller produkt."], },
      { heading: "Skilj på smart ljuskälla och fast styrning", paragraphs: ["En smart lampa med stickpropp eller vanlig lampsockel är en lös produkt, medan en infälld dimmer eller en ny väggbrytare hör till den fasta installationen. Att en produkt kan styras trådlöst gör inte automatiskt installationen till ett hemmajobb. Berätta för elektrikern vilken funktion du vill uppnå, inte bara vilket fabrikat du tänker köpa."], },
      { heading: "Samordna med övrigt byggarbete", paragraphs: ["Placering av lampor, drivdon, uttag och eventuella reglage behöver bestämmas innan tak och väggar stängs. Tänk också på hur lösningen ska fungera om internet eller en app inte är tillgänglig. Undvik att täcka in komponenter eller skapa åtkomst som kräver rivning vid framtida service."], steps: ["Beskriv ljussituationer rum för rum.", "Markera var belysning och reglage ska finnas.", "Låt elföretaget hantera fasta ändringar.", "Spara produkt- och installationsinformation."] },
      { heading: "Välj hela och kompatibla produkter", paragraphs: ["Följ alltid tillverkarens anvisningar och använd produkter som passar armatur, ljuskälla och styrning. Flimmer, surr, överhettning eller störningar är skäl att sluta använda den berörda produkten och utreda orsaken. Öppna inte drivdon, dimrar eller fast installerade delar själv."], },
    ],
    sourceLabel: "Elsäkerhetsverket: Vad får jag göra själv med el?",
    sourceUrl: "https://www.elsakerhetsverket.se/privatpersoner/detta-far-du-gora-sjalv-med-el/vad-far-jag-gora-sjalv-med-el/",
  },
  {
    slug: "installera-smart-strombrytare",
    publishedAt: "2026-06-17",
    updatedLabel: "Uppdaterad 17 juni 2026",
    title: "Installera smart strömbrytare – regler för fast el och gör-det-själv",
    description: "En smart strömbrytare är ofta del av den fasta installationen. Här är gränsen mellan tillåtet byte och arbete för elföretag.",
    category: "Smarta hem",
    readTime: "5 min läsning",
    accent: "amber",
    intro: "Smarta strömbrytare gör det möjligt att styra belysning med schema, app eller trådlös knapp. Men tekniken förändrar inte elsäkerhetsreglerna. Börja därför med att avgöra om det handlar om ett rent byte av en befintlig brytare eller om funktionen kräver ändrad fast installation.",
    safetyNote: "Nya brytare, ändrad kabeldragning, nya dosor eller osäkerhet kring befintliga ledare ska alltid hanteras av ett registrerat elföretag.",
    sections: [
      { heading: "Ett befintligt byte har snäva villkor", paragraphs: ["Elsäkerhetsverket anger att en befintlig strömbrytare för högst 16 A i egen kapsling eller dosa kan få bytas av den som har rätt kunskap och kan kontrollera arbetet korrekt. Det är inte ett generellt tillstånd att installera valfri smart brytare. Läs förutsättningarna noga och anlita elföretag om något är oklart."], },
      { heading: "Ny funktion kan innebära mer än ett byte", paragraphs: ["Många smarta lösningar behöver ändrad styrning, ytterligare komponenter, nya ledare eller annan placering. Då är det en förändring av den fasta installationen. Beskriv i stället önskad funktion för elektrikern: vilka lampor som ska styras, var reglage behövs och hur lösningen ska fungera utan telefon."], },
      { heading: "Bryt spänningen och chansa aldrig", paragraphs: ["Även när ett arbete är tillåtet förutsätter det kunskap och säker frånkoppling. Elsäkerhetsverket betonar att spänningen ska brytas och kontrolleras innan arbetet påbörjas. Sprucken isolering, skadade ledare, okända färger eller en dosa som inte stämmer med produkten är tydliga skäl att avbryta."], steps: ["Avgör om det är ett rent befintligt byte.", "Kontrollera produktens krav och din egen kunskap.", "Avbryt vid osäkerhet eller skadade delar.", "Anlita registrerat elföretag för ändringar i fast installation."] },
      { heading: "Dokumentera den färdiga funktionen", paragraphs: ["När ett elföretag har gjort installationen bör du spara produktinformation och anteckna vilken belysning som styrs. Det förenklar service, framtida ändringar och felsökning. Om brytaren blir varm, glappar, låter eller beter sig oväntat ska den inte öppnas eller användas vidare som vanligt."], },
    ],
    sourceLabel: "Elsäkerhetsverket: Byta infälld strömbrytare",
    sourceUrl: "https://www.elsakerhetsverket.se/privatpersoner/detta-far-du-gora-sjalv-med-el/byta-infalld-strombrytare/",
  },
  {
    slug: "smarta-hem-stor-wifi-eller-radio",
    publishedAt: "2026-06-18",
    updatedLabel: "Uppdaterad 18 juni 2026",
    title: "Smarta hem stör wifi eller radio – så avgränsar du problemet säkert",
    description: "Så dokumenterar du misstänkta störningar från smarta hem-produkter utan att öppna dem eller ändra fast el själv.",
    category: "Smarta hem",
    readTime: "5 min läsning",
    accent: "green",
    intro: "Smarta hem-produkter kan kommunicera trådlöst och innehålla elektronik som, om något är fel, påverkar radio, wifi eller annan utrustning. En metodisk kontroll hjälper dig att beskriva sambandet utan att göra riskfyllda ingrepp i produkter eller elinstallation.",
    safetyNote: "Öppna inte smarta brytare, drivdon, laddare eller centraler för att leta efter en störning. Sluta använda produkten direkt om störningen kombineras med värme, lukt, skada eller missfärgning.",
    sections: [
      { heading: "Leta efter ett tydligt mönster", paragraphs: ["Notera vad som påverkas, när problemet börjar och om det sammanfaller med att en viss produkt ansluts, laddar eller aktiveras. Jämför med normal av- och påslagning eller urkoppling av en lös produkt i taget, när det kan göras säkert. Ändra inte flera saker samtidigt; då blir resultatet svårt att tolka."], },
      { heading: "Skilj på nätverksproblem och elektriska störningar", paragraphs: ["Trådlösa problem kan bero på täckning och många samtidiga användare, medan elektromagnetiska störningar ofta visar ett tydligare samband med en viss produkt. Dokumentera avstånd, tid, berörd utrustning och produktens modell. En kort film eller logg kan vara mer användbar än att försöka reparera något själv."], },
      { heading: "Hantera fasta produkter på rätt sätt", paragraphs: ["Om den misstänkta produkten är en fast brytare, dimmer eller annan del av elanläggningen ska du inte demontera den för test. Kontakta ett registrerat elföretag om den fasta installationen behöver bedömas. För en lös produkt kan du vända dig till säljaren med dokumenterade uppgifter och följa deras anvisningar."], steps: ["Skriv ner tidpunkt och berörd utrustning.", "Ändra en säker, lös produkt i taget.", "Spara modell- och inköpsuppgifter.", "Ta hjälp av säljare eller elföretag beroende på produktens anslutning."] },
      { heading: "Säkerhet går före felsökning", paragraphs: ["En produkt som stör men också blir varm, luktar bränt, sprakar eller har skadat hölje ska tas ur bruk. Störningar kan vara ett tecken på produktproblem, men du ska inte försöka bekräfta det genom att öppna höljet eller kringgå skydd. Vid rök, brand eller akut fara gäller 112."], },
    ],
    sourceLabel: "Elsäkerhetsverket: EMC – för att samhället ska fungera",
    sourceUrl: "https://www.elsakerhetsverket.se/om-oss/press/nyheter/2023/emc--for-att-samhallet-ska-fungera/",
  },
];
