import type { GuidePost } from "./posts";

export const outdoorGuidePosts: GuidePost[] = [
  {
    slug: "el-pa-campingplats-husvagn-husbil",
    publishedAt: "2026-06-10",
    updatedLabel: "Uppdaterad 10 juni 2026",
    title: "El på campingplats – anslut husvagn och husbil säkert",
    description: "En trygg checklista för campingel: uttag, jordfelsbrytare, kabel och kontroll före anslutning.",
    category: "Utomhus",
    readTime: "5 min läsning",
    accent: "green",
    intro: "Elinstallationerna i husvagnar och husbilar utsätts för vibrationer, fukt och slitage. Innan du ansluter på campingplatsen behöver både platsens uttag, din kabel och fordonets anslutning vara hela och rätt anpassade.",
    safetyNote: "Anslut inte om uttaget, kabeln eller kontakten är sprucken, varm, missfärgad eller lös. Felanmäl campingplatsens uttag i stället för att försöka rätta till det.",
    sections: [
      { heading: "Kontrollera uttaget före inkoppling", paragraphs: ["Titta först att campinguttaget är helt och att lucka, kapsling och kontakt ser oskadade ut. Elsäkerhetsverket rekommenderar jordfelsbrytare för uttag till husvagnar och husbilar. Kontrollera, om du får och kan göra det säkert, att skyddet löser när testknappen trycks in innan uttaget används."], steps: ["Kontrollera uttagets skick utan att öppna det.", "Testa jordfelsbrytaren enligt anvisningen.", "Felanmäl direkt om testet inte bryter strömmen."] },
      { heading: "Använd rätt kabel hela vägen", paragraphs: ["Kabeln ska vara avsedd för utomhusbruk och vara hel från kontakt till fordon. Dra den så att den inte kläms i dörrar, ligger i vatten eller blir en snubbelrisk. En skadad kabel ska tas ur bruk; tejp eller provisoriska skarvar gör den inte säker."] },
      { heading: "Tänk på fukt och belastning", paragraphs: ["Fukt gör att ström leds bättre och ökar risken om en produkt eller anslutning har fel. Håll kopplingar från mark och vatten och använd inte inomhusprodukter i tält eller förtält om miljön inte motsvarar en torr inomhusmiljö."] },
      { heading: "Om något löser ut", paragraphs: ["Koppla bort den egna utrustningen om det kan göras säkert och berätta för campingvärden vad som hände. Återställ inte ett skydd upprepade gånger. Om felet verkar följa fordonet behöver dess elanläggning eller produkt bedömas innan fortsatt användning."] },
    ],
    sourceLabel: "Elsäkerhetsverket: Säker el på semestern",
    sourceUrl: "https://www.elsakerhetsverket.se/privatpersoner/du-ar-ansvarig-for-elen/saker-el-pa-semestern/",
  },
  {
    slug: "portabel-jordfelsbrytare-utomhus",
    publishedAt: "2026-06-11",
    updatedLabel: "Uppdaterad 11 juni 2026",
    title: "Portabel jordfelsbrytare utomhus – när är den rätt extra skydd?",
    description: "Så använder du en portabel jordfelsbrytare säkrare vid trädgårdsarbete, belysning och andra utomhusprodukter.",
    category: "Jordfelsbrytare",
    readTime: "5 min läsning",
    accent: "green",
    intro: "En portabel jordfelsbrytare ansluts mellan ett vägguttag och en elektrisk produkt. Den kan vara ett viktigt extra skydd utomhus, särskilt i äldre anläggningar eller när en lång utomhuskabel används.",
    safetyNote: "En portabel jordfelsbrytare ersätter inte ett jordat uttag, rätt utomhusmateriel eller en hel kabel. Använd aldrig en lösning som kringgår skyddsjord.",
    sections: [
      { heading: "Välj en brytare för personsäkerhet", paragraphs: ["Elsäkerhetsverket anger att en portabel jordfelsbrytare för personsäkerhet ska vara märkt 0,03 A eller 30 mA. Läs tillverkarens anvisning och använd den bara på ett jordat uttag som är anpassat för utomhusmiljö."] },
      { heading: "Koppla den på rätt plats", paragraphs: ["Anslut brytaren direkt vid uttaget och därefter den utomhusgodkända kabeln eller produkten. Den kan minska följden av ett jordfel långt bort på en kabel och gör att endast den anslutna delen bryts, inte nödvändigtvis hela huset."], steps: ["Kontrollera uttag, brytare och kabel visuellt.", "Testa brytaren enligt tillverkarens anvisning.", "Anslut en hel produkt avsedd för utomhusbruk."] },
      { heading: "Testa regelbundet", paragraphs: ["Tryck på testknappen minst två gånger per år, eller så ofta tillverkaren anger. Strömmen ska då brytas. Om en portabel jordfelsbrytare inte fungerar ska den inte användas utan lämnas tillbaka eller till elåtervinning och ersättas."] },
      { heading: "När en fast lösning behövs", paragraphs: ["Återkommande behov av extra skydd kan vara ett skäl att låta ett registrerat elinstallationsföretag bedöma den fasta anläggningen. En fast jordfelsbrytare får inte installeras av privatperson."] },
    ],
    sourceLabel: "Elsäkerhetsverket: Jordfelsbrytaren – din säkerhet",
    sourceUrl: "https://www.elsakerhetsverket.se/privatpersoner/din-elanlaggning/om-du-ager-din-bostad/jordfelsbrytaren-din-sakerhet/om-jordfelsbrytare/",
  },
  {
    slug: "anvanda-elverktyg-utomhus-i-regn",
    publishedAt: "2026-06-12",
    updatedLabel: "Uppdaterad 12 juni 2026",
    title: "Använda elverktyg utomhus i regn – när ska arbetet vänta?",
    description: "Praktiska säkerhetsråd för eldrivna trädgårdsverktyg när marken, verktyget eller vädret är fuktigt.",
    category: "Utomhus",
    readTime: "5 min läsning",
    accent: "amber",
    intro: "Fuktig mark, blöta händer och ett skadat hölje gör elarbete utomhus mer riskfyllt. Att ett verktyg är avsett för utomhusbruk betyder inte alltid att det är fuktskyddat eller lämpligt att använda när det regnar.",
    safetyNote: "Arbeta aldrig barfota med elverktyg utomhus. Avbryt direkt om det börjar regna, om verktyget blir fuktigt eller om kabeln får en skada.",
    sections: [
      { heading: "Läs vad verktyget faktiskt tål", paragraphs: ["Kontrollera bruksanvisning och märkning innan arbetet börjar. Elsäkerhetsverket lyfter att vissa handverktyg för utomhusbruk, exempelvis häcksaxar och borrmaskiner, ändå inte är fuktskyddade och därför bara bör användas när det är torrt."] },
      { heading: "Gör en kontroll före start", paragraphs: ["Se efter sprickor i kabel och hölje, glapp kontakt och skadad dragavlastning. Använd bara jordad kabel som är avsedd för utomhusbruk och skydda den mot klämning. En jordfelsbrytare är ett viktigt tilläggsskydd, inte ett tillstånd att använda skadad utrustning."], steps: ["Kontrollera verktyg, stickpropp och kabel.", "Placera kabeln där den hålls synlig och bakom dig.", "Avstå om mark, verktyg eller anslutningar är blöta."] },
      { heading: "Avsluta på ett säkert sätt", paragraphs: ["Stäng av verktyget och dra ur stickproppen när arbetet är klart eller vädret slår om. Dra i stickproppen, inte i kabeln. Låt produkten torka och undersökas om den blivit genomblöt eller om jordfelsbrytaren har löst ut."] },
      { heading: "När du ska ta hjälp", paragraphs: ["En kabel, kontakt eller fast anslutning som är skadad ska inte repareras provisoriskt. Kontakta service eller ett registrerat elinstallationsföretag beroende på vad som har skadats."] },
    ],
    sourceLabel: "Elsäkerhetsverket: Säker el utomhus",
    sourceUrl: "https://www.elsakerhetsverket.se/privatpersoner/du-ar-ansvarig-for-elen/saker-el-utomhus/",
  },
  {
    slug: "planera-tradgardsbelysning-sakert",
    publishedAt: "2026-06-13",
    updatedLabel: "Uppdaterad 13 juni 2026",
    title: "Planera trädgårdsbelysning – jordning, IP-klass och trygg installation",
    description: "Så planerar du säker trädgårdsbelysning med rätt anslutning, fuktskydd och hjälp för fasta elarbeten.",
    category: "Utomhus",
    readTime: "6 min läsning",
    accent: "blue",
    intro: "Trädgårdsbelysning ska fungera genom regn, kyla och mörka månader utan att kablar eller anslutningar blir en risk. Börja med att skilja flyttbara produkter från den fasta installation som behöver planeras och utföras av rätt företag.",
    safetyNote: "Koppla inte dekorationsbelysning på balkong, terrass eller i trädgård till ett ojordat uttag inomhus. Det kan göra en felaktig produkt farlig.",
    sections: [
      { heading: "Bestäm vad som ska vara fast", paragraphs: ["Nya fasta ljuspunkter, uttag och ledningar utomhus är elinstallationsarbete. Ta in ett registrerat elinstallationsföretag tidigt, så att placering, materiel och framtida behov kan lösas utan synliga provisoriska kablar."] },
      { heading: "Välj produkter för miljön", paragraphs: ["Kontrollera att belysning, transformator och eventuella skarvsladdar uttryckligen är avsedda för utomhusbruk. Flyttbara trädgårdsprodukter bör enligt Elsäkerhetsverket vara märkta minst IP44. Läs även svensk bruksanvisning och kontrollera CE-märkning."] },
      { heading: "Anslut med jordning och jordfelsbrytare", paragraphs: ["All utomhusbelysning ska anslutas till jordade uttag och bör skyddas av jordfelsbrytare. Om det saknas skydd vid uttaget kan en portabel jordfelsbrytare för utomhusbruk vara ett extra skydd för flyttbara produkter."], steps: ["Kontrollera jordat uttag och fungerande jordfelsbrytare.", "Håll kontakter och kopplingar från vatten och mark.", "Se till att kablar inte kan klämmas eller bli snubbelrisker."] },
      { heading: "Kontrollera inför varje säsong", paragraphs: ["Titta efter sprickor, missfärgning, skadade stickproppar och lösa fästen innan du tänder. Byt bara ljuskällor med samma form och spänning som armaturen är avsedd för. Sluta använda sådan utrustning som ser skadad ut."] },
    ],
    sourceLabel: "Elsäkerhetsverket: Belysning utomhus",
    sourceUrl: "https://www.elsakerhetsverket.se/privatpersoner/dina-elprodukter/produkter/belysning/belysning-utomhus/",
  },
  {
    slug: "elektrisk-fontan-tradgard-elsakerhet",
    publishedAt: "2026-06-14",
    updatedLabel: "Uppdaterad 14 juni 2026",
    title: "Elektrisk fontän i trädgården – säker anslutning nära vatten",
    description: "Kontrollera fontän, pump, kabel och jordfelsbrytare innan du använder el nära damm, vatten och våt mark.",
    category: "Utomhus",
    readTime: "5 min läsning",
    accent: "blue",
    intro: "En trädgårdsfontän kombinerar vatten, fuktig mark och elektrisk utrustning. Säkerheten avgörs både av att produkten är avsedd för platsen och av hur den ansluts och kontrolleras över tid.",
    safetyNote: "Rör inte pump, kontakt eller belysning om du misstänker fel eller om utrustningen ligger i vatten. Bryt strömmen endast från en torr och säker plats.",
    sections: [
      { heading: "Kontrollera produkt och anvisning", paragraphs: ["Fontän, pump och belysning ska vara avsedda för utomhusmiljö och ha tydlig märkning samt svensk bruksanvisning. Följ tillverkarens instruktioner för placering, montage och användning i stället för att gissa hur delarna ska sitta."] },
      { heading: "Anslut till rätt skydd", paragraphs: ["Elektriska produkter utomhus ska anslutas till ett jordat uttag och skyddas av jordfelsbrytare. Använd inte ett ojordat uttag inomhus med en kabel dragen ut till trädgården. Kabel och stickpropp ska vara hela och anpassade för utomhusbruk."] },
      { heading: "Håll anslutningen torr och skyddad", paragraphs: ["Placera inte skarvar där de kan hamna i vatten, täckas av löv eller utsättas för klämning. Dra kabeln så att den inte blir en fallrisk och ta bort den innan gräset klipps eller arbete sker runt dammen."], steps: ["Kontrollera kabel, kontakt och hölje före inkoppling.", "Testa jordfelsbrytaren enligt anvisningen.", "Koppla ur och undersök vid fukt, sprickor eller utlösning."] },
      { heading: "Agera vid en avvikelse", paragraphs: ["Värme, bränd lukt, återkommande utlösning eller skadat hölje är skäl att sluta använda produkten. Byt inte fasta uttag eller ledningar själv; låt ett registrerat elinstallationsföretag bedöma den fasta delen."] },
    ],
    sourceLabel: "Elsäkerhetsverket: Säker el utomhus",
    sourceUrl: "https://www.elsakerhetsverket.se/privatpersoner/du-ar-ansvarig-for-elen/saker-el-utomhus/",
  },
  {
    slug: "ladda-elbil-vid-fritidshus",
    publishedAt: "2026-06-15",
    updatedLabel: "Uppdaterad 15 juni 2026",
    title: "Ladda elbil vid fritidshus – planera för säker laddning",
    description: "Så laddar du elbilen säkrare vid sommarstugan eller fjällstugan och undviker långvarig laddning i vanligt uttag.",
    category: "Laddning",
    readTime: "5 min läsning",
    accent: "green",
    intro: "Fritidshus har ofta äldre elanläggningar och saknar ibland en laddpunkt för bil. Det gör det särskilt viktigt att planera laddningen innan resan, i stället för att låta bilen belasta ett vanligt vägguttag länge och återkommande.",
    safetyNote: "Elsäkerhetsverket avråder från att ladda elbil i ett vanligt vägguttag. Använd inte skarvsladd som ersättning för en laddpunkt.",
    sections: [
      { heading: "Ta reda på förutsättningarna före resan", paragraphs: ["Kontrollera om stugan har en installerad laddpunkt och planera annars var du kan ladda på vägen eller i närheten. Ett vanligt uttag är gjort för allmänbruk och inte för regelbundna, långvariga höga laster från elbilsladdning."] },
      { heading: "Välj en riktig laddpunkt för återkommande behov", paragraphs: ["Om bilen ska laddas vid fritidshuset regelbundet är en laddbox den säkra långsiktiga lösningen. Ett registrerat elinstallationsföretag kan bedöma den befintliga anläggningen, laddplatsen och om lastbegränsning behövs."] },
      { heading: "Var extra försiktig i äldre stugor", paragraphs: ["I en äldre stuga kan jordfelsbrytare saknas och uttag eller kablar vara slitna. Kontrollera synliga delar utan att öppna dem, och använd inte en anläggning som har lösa uttag, skadad kabel, bränd lukt eller återkommande utlösta skydd."], steps: ["Planera offentlig eller installerad laddning före resan.", "Kontrollera att laddpunkt och kabel är hela.", "Avbryt och ta hjälp vid värme, lukt eller utlöst skydd."] },
      { heading: "Lämna inte ett fel för nästa besök", paragraphs: ["Dokumentera vad som hände och låt felet utredas innan laddning återupptas. Att en säkring går att återställa visar inte att anläggningen är dimensionerad eller säker för laddning."] },
    ],
    sourceLabel: "Elsäkerhetsverket: Elsäkert sportlov",
    sourceUrl: "https://www.elsakerhetsverket.se/privatpersoner/dina-elprodukter/anvanda-elprodukter/elsakert-sportlov/",
  },
  {
    slug: "lastbalansering-laddbox-vad-ar-det",
    publishedAt: "2026-06-16",
    updatedLabel: "Uppdaterad 16 juni 2026",
    title: "Lastbalansering till laddbox – vad är det och när behövs den?",
    description: "Förstå hur lastbalansering kan minska risken för överbelastning när elbilen laddas hemma.",
    category: "Laddning",
    readTime: "5 min läsning",
    accent: "green",
    intro: "När en elbil laddas samtidigt som spis, värmepump eller andra stora laster används kan belastningen på bostadens elinstallation bli hög. Lastbalansering eller lastbegränsning är en del av planeringen som hjälper laddningen att fungera inom anläggningens förutsättningar.",
    safetyNote: "Försök inte lösa återkommande säkringsproblem genom att höja säkring eller ändra laddinställningar på egen hand. Det kan göra att skydd och ledningar belastas fel.",
    sections: [
      { heading: "Utgå från husets verkliga belastning", paragraphs: ["Laddboxens effekt är inte den enda frågan. Elektrikern behöver bedöma huvudsäkring, befintliga stora förbrukare och när de används. Lastbalansering kan begränsa laddningen när huset använder mycket el och ge mer laddning när belastningen sjunker."] },
      { heading: "Ta med frågan i offertunderlaget", paragraphs: ["Beskriv värmepump, spis, elektrisk uppvärmning, solceller och andra stora laster när du begär offert. Elsäkerhetsverket lyfter lastbalansering eller lastbegränsning som en av de frågor som bör planeras före installation av laddpunkt."] },
      { heading: "Låt rätt företag installera", paragraphs: ["En laddbox och utrustning som hör till den fasta elanläggningen ska installeras av ett registrerat elinstallationsföretag. Kontrollera företaget i Kolla elföretaget och be om en tydlig genomgång av hur laddningen ska fungera i din anläggning."], steps: ["Samla uppgifter om stora förbrukare.", "Beskriv när bilen normalt laddas.", "Be om förklaring av föreslagen lastbegränsning.", "Spara dokumentation efter installationen."] },
      { heading: "Följ upp avvikande beteende", paragraphs: ["Säkringar eller jordfelsbrytare som löser ut, varma uttag eller felmeddelanden ska inte ignoreras. Sluta ladda om något verkar fel och kontakta installatör eller service enligt produktens anvisning."] },
    ],
    sourceLabel: "Elsäkerhetsverket: Installation av elbilsladdare",
    sourceUrl: "https://www.elsakerhetsverket.se/privatpersoner/din-elanlaggning/bygga-och-renovera/installation-av-elbilsladdare/",
  },
  {
    slug: "laddbox-i-carport-sakert",
    publishedAt: "2026-06-17",
    updatedLabel: "Uppdaterad 17 juni 2026",
    title: "Laddbox i carport – planera placering, kabel och skydd",
    description: "Vad du bör ta upp med elektrikern när laddboxen ska sitta i en carport eller vid en öppen parkeringsplats.",
    category: "Laddning",
    readTime: "5 min läsning",
    accent: "blue",
    intro: "En carport är delvis utomhusmiljö. Laddpunkten ska därför planeras med hänsyn till väder, påkörningsrisk, kabelväg och den befintliga elanläggningen – inte bara efter var bilen råkar stå.",
    safetyNote: "Montera inte en laddbox själv och gör inga egna ändringar i fast kabel, säkring eller elcentral. Laddutrustning ska installeras av ett registrerat elinstallationsföretag.",
    sections: [
      { heading: "Visa platsen för elektrikern", paragraphs: ["Gå igenom var bilen parkerar, var laddkabeln ska hanteras och vilka delar som kan utsättas för regn, snö eller påkörning. Elektrikern kan bedöma placeringen, kabeldragningen och om anläggningen behöver kompletteras med exempelvis lastbegränsning eller överspänningsskydd."] },
      { heading: "Undvik slitage på kabel och kontakt", paragraphs: ["Kabeln ska inte klämmas i dörrar, ligga där bilen kör eller lämnas skadad på marken. Kontrollera regelbundet hölje, anslutning och kabel utan att öppna laddboxen. Värme, sprickor, missfärgning eller felmeddelanden är signaler att sluta använda laddpunkten tills den har bedömts."] },
      { heading: "Tänk utomhus även under tak", paragraphs: ["En carport är inte ett torrt rum bara för att den har tak. Materiel och placering behöver tåla den miljö där de används, och fasta elarbeten utomhus omfattas av samma krav på rätt utförande som inomhus."], steps: ["Dokumentera parkerings- och kabelväg före offert.", "Kontrollera att företaget är registrerat.", "Be om dokumentation och genomgång när arbetet är klart."] },
      { heading: "Använd bara laddpunkten för bilen", paragraphs: ["En laddbox är avsedd för laddningsbara bilar och är en säkrare lösning än långvarig laddning från vanligt vägguttag. Använd inte skarvsladd eller adapter för att skapa en tillfällig bilanslutning."] },
    ],
    sourceLabel: "Elsäkerhetsverket: Installation av elbilsladdare",
    sourceUrl: "https://www.elsakerhetsverket.se/privatpersoner/din-elanlaggning/bygga-och-renovera/installation-av-elbilsladdare/",
  },
  {
    slug: "solceller-efter-storm-kontroll",
    publishedAt: "2026-06-18",
    updatedLabel: "Uppdaterad 18 juni 2026",
    title: "Solceller efter storm – kontrollera anläggningen utan att gå på taket",
    description: "Så dokumenterar du synliga skador efter hårt väder och vet när solcellsanläggningen behöver professionell kontroll.",
    category: "Solceller",
    readTime: "5 min läsning",
    accent: "amber",
    intro: "Hård vind, nedfallna grenar och skador på tak kan påverka en solcellsanläggning även om elproduktionen fortfarande verkar fungera. Efter ett oväder ska du prioritera avstånd, synlig kontroll från marken och rätt hjälp – inte egen felsökning på taket.",
    safetyNote: "Rör inte paneler, kablar, kontakter eller delar som fallit ner. Solcellsanläggningen kan ha spänningssatta delar även när annan el är bruten.",
    sections: [
      { heading: "Kontrollera från säker marknivå", paragraphs: ["Titta efter synliga lösa paneler, hängande kablar, skadat takmaterial eller delar som hamnat på marken. Fotografera på avstånd om det kan göras utan att gå in i ett riskområde. Klättra inte upp på taket och öppna inte växelriktare eller brytare."] },
      { heading: "Avgränsa vid akut fara", paragraphs: ["Håll människor och djur borta från nedfallna delar och kontakta 112 vid akut fara, brand eller nedfallen ledning. Vid mindre men misstänkta skador kontaktar du installatör eller ett företag med rätt kompetens för solcellsanläggningar."] },
      { heading: "Spara underlag för bedömning", paragraphs: ["Notera när stormen inträffade, vad du kan se och om växelriktaren visar larm. Spara bilder och tidigare dokumentation. Det ger installatören bättre möjlighet att avgöra vad som behöver kontrolleras utan att du gör ett riskfyllt ingrepp."], steps: ["Håll avstånd och kontrollera visuellt.", "Dokumentera synliga skador och larm.", "Kontakta rätt företag för bedömning.", "Ta inte anläggningen i normal drift igen om den bedöms skadad."] },
      { heading: "Förebygg nästa kontrollbehov", paragraphs: ["Som innehavare ansvarar du för fortlöpande kontroll och underhåll. Spara ritningar, produktuppgifter och kontaktvägar, och låt brister i kablar, kontakter eller infästning hanteras professionellt."] },
    ],
    sourceLabel: "Elsäkerhetsverket: Säkerhetsrisker med solcellsanläggningar",
    sourceUrl: "https://www.elsakerhetsverket.se/privatpersoner/din-elanlaggning/bygga-och-renovera/installation-av-solceller/vilka-sakerhetsrisker-finns/",
  },
  {
    slug: "reservkraft-med-solceller",
    publishedAt: "2026-06-19",
    updatedLabel: "Uppdaterad 19 juni 2026",
    title: "Reservkraft med solceller – varför krävs särskild planering?",
    description: "Förstå skillnaden mellan vanliga nätanslutna solceller och reservkraft vid strömavbrott.",
    category: "Solceller",
    readTime: "6 min läsning",
    accent: "green",
    intro: "En vanlig nätansluten solcellsanläggning ska koppla ner sig vid strömavbrott. Vill du ha reservkraft behöver anläggningen planeras för det från början, med säker frånskiljning och rätt utförande.",
    safetyNote: "Försök aldrig skapa reservkraft genom egna kopplingar mellan solceller, batteri, växelriktare och husets elcentral. Felaktig matning kan vara farlig för både dig och personer som arbetar på elnätet.",
    sections: [
      { heading: "Varför solelen normalt stängs av", paragraphs: ["Solcellsanläggningar som går parallellt med elnätet ska automatiskt koppla ner sig när nätet försvinner. Det hindrar att anläggningen oavsiktligt matar ut ström på elnätet under ett avbrott."] },
      { heading: "Reservkraft är en annan funktion", paragraphs: ["Reservkraft eller fristående drift ställer andra krav på elinstallationen. Elsäkerhetsverket beskriver bland annat behov av säker frånskiljning och eget jordtag. Ett batterilager kan också behövas för att hantera variationer mellan produktion och användning."] },
      { heading: "Beskriv behovet före offert", paragraphs: ["Fundera på vilka funktioner som faktiskt ska hållas igång, hur länge och vad som ska hända när nätet kommer tillbaka. Ge den informationen till ett registrerat elföretag som är rätt registrerat för arbetet med elproduktionsanläggningar."], steps: ["Lista de funktioner som behöver reservkraft.", "Be om en lösning med tydlig frånskiljning.", "Kontrollera företagets registrering och verksamhetstyp.", "Spara överlämnad dokumentation och instruktioner."] },
      { heading: "Ta inte reservdrift för given", paragraphs: ["Att ha solceller eller batteri betyder inte automatiskt att huset har el vid ett avbrott. Följ den färdiga anläggningens instruktioner och låt installatören reda ut larm, ändringar eller osäker funktion."] },
    ],
    sourceLabel: "Elsäkerhetsverket: Planera din solcellsanläggning",
    sourceUrl: "https://www.elsakerhetsverket.se/privatpersoner/din-elanlaggning/bygga-och-renovera/installation-av-solceller/planera-din-solcellsanlaggning/",
  },
];
