import type { GuidePost } from "./posts";

export const searchConsoleGuidePosts: GuidePost[] = [
  {
    slug: "byta-vaggkontakt-eller-vagguttag",
    title: "Byta väggkontakt eller vägguttag – vad menas och vad får du göra?",
    description: "Många söker på väggkontakt men menar vägguttag. Här reder vi ut begrepp, regler och när elektriker behövs.",
    category: "Elinstallation",
    readTime: "5 min läsning",
    publishedAt: "2026-08-23",
    updatedLabel: "Uppdaterad 23 augusti 2026",
    accent: "amber",
    intro: "Ordet väggkontakt används ofta i vardagligt tal, men kan betyda flera saker: vägguttag, stickpropp eller ibland hela anslutningen mellan produkt och uttag. Innan något byts behöver du veta vilken del det handlar om och om arbetet berör den fasta elanläggningen.",
    safetyNote: "Ta inte loss kåpa, uttag eller strömbrytare om du är osäker på vad delen heter, hur den är ansluten eller hur arbetet kontrolleras säkert.",
    sections: [
      { heading: "Börja med rätt begrepp", paragraphs: ["Vägguttaget sitter fast i väggen. Stickproppen sitter på sladden till en produkt. Ett sladduttag eller en skarvkontakt hör till lös utrustning. Gränsen är viktig eftersom fast elinstallation omfattas av andra regler än arbete på en lös produkt."] },
      { heading: "Byte är inte alltid samma sak", paragraphs: ["Ett rent byte av ett befintligt vägguttag har snäva förutsättningar och kräver tillräcklig kunskap. Om uttaget ska flyttas, jordas, kompletteras, repareras bakom dosan eller bytas på grund av skada är det inte längre ett enkelt byte."] },
      { heading: "När ska du avstå direkt?", paragraphs: ["Avstå om uttaget är varmt, missfärgat, sprucket, sitter löst, luktar bränt eller om säkring eller jordfelsbrytare löser ut när uttaget används. Då behöver orsaken bedömas, inte bara den synliga delen bytas."], steps: ["Identifiera om det gäller vägguttag, stickpropp eller lös sladddel.", "Kontrollera om det finns värme, lukt, glapp eller skada.", "Anlita registrerat elföretag vid osäkerhet eller fast ändring."] },
      { heading: "Sök rätt hjälp snabbare", paragraphs: ["När du kontaktar elektriker, beskriv platsen, symtomet och vad som är anslutet. Säg gärna att du menar vägguttag om delen sitter fast i väggen. Det gör felsökningen tydligare och minskar risken för missförstånd redan vid första kontakten."] },
    ],
    sourceLabel: "Elsäkerhetsverket: Vad får jag göra själv med el?",
    sourceUrl: "https://www.elsakerhetsverket.se/privatpersoner/detta-far-du-gora-sjalv-med-el/vad-far-jag-gora-sjalv-med-el/",
  },
  {
    slug: "gruppcentral-hemma",
    title: "Gruppcentral hemma – vad är det och när behöver den kontrolleras?",
    description: "Förstå gruppcentralens roll, vanliga varningssignaler och när en elektriker bör kontrollera eller byta den.",
    category: "Elcentral",
    readTime: "5 min läsning",
    publishedAt: "2026-08-23",
    updatedLabel: "Uppdaterad 23 augusti 2026",
    accent: "blue",
    intro: "Gruppcentralen är den del av elanläggningen där bostadens grupper, säkringar och skydd samlas. Den kan kallas elcentral, proppskåp eller säkringsskåp i vardagligt tal. När den är tydlig och i gott skick blir både vardaglig kontroll och akut felsökning enklare.",
    safetyNote: "Öppna inte centralens kapsling och gör inga egna ingrepp i ledningar eller komponenter. Bränd lukt, värme, knaster eller återkommande frånslag ska bedömas skyndsamt.",
    sections: [
      { heading: "Vad finns i en gruppcentral?", paragraphs: ["I en vanlig bostad kan centralen innehålla huvudbrytare, gruppsäkringar, jordfelsbrytare, märkning och ibland extra skydd för särskild utrustning. Exakt utförande beror på anläggningens ålder och hur den har byggts om över tid."] },
      { heading: "Tecken på att centralen bör ses över", paragraphs: ["Otydlig märkning, återkommande säkringar som löser ut, lösa lock, missfärgning, värme, surr eller knaster är signaler att ta på allvar. Det gäller särskilt om problemen uppstår vid normal användning och kommer tillbaka efter återställning."] },
      { heading: "Byte eller komplettering?", paragraphs: ["En gammal central behöver inte alltid bytas bara för att den är äldre, men nya behov kan förändra förutsättningarna. Laddbox, solceller, golvvärme, köksrenovering eller fler effektkrävande produkter kan göra att centralen behöver bedömas innan arbetet planeras."], steps: ["Notera vilka grupper som påverkas.", "Fotografera märkning och synligt skick utan att öppna centralen.", "Be registrerat elföretag bedöma centralen vid återkommande problem."] },
      { heading: "Förbered inför elektrikerbesök", paragraphs: ["Ha gärna gruppförteckning, tidigare dokumentation och en kort beskrivning av felet redo. Berätta om felet är akut, när det uppstår och vilka produkter som används samtidigt. Då kan elektrikern snabbare avgöra om det handlar om belastning, skydd, produktfel eller fast installation."] },
    ],
    sourceLabel: "Elsäkerhetsverket: Elcentralen",
    sourceUrl: "https://www.elsakerhetsverket.se/privatpersoner/din-elanlaggning/om-du-ager-din-bostad/elcentralen/",
  },
  {
    slug: "projektering-solceller-elfragor",
    title: "Projektering av solceller – elfrågor att lösa före offert",
    description: "Inför solceller behöver elcentral, huvudsäkring, kabelväg och dokumentation kontrolleras tidigt.",
    category: "Solceller",
    readTime: "6 min läsning",
    publishedAt: "2026-08-23",
    updatedLabel: "Uppdaterad 23 augusti 2026",
    accent: "green",
    intro: "Projektering av solceller handlar inte bara om takyta och paneler. Den befintliga elanläggningen, elcentralen, huvudsäkringen, kabelvägen och framtida service behöver vägas in innan offerten blir meningsfull.",
    safetyNote: "Gör inga egna ingrepp i elcentral, mätarskåp eller befintlig solcellsutrustning. Solcellsanläggningar kan ha spänningssatta delar även när huset verkar frånkopplat.",
    sections: [
      { heading: "Samla underlag om elanläggningen", paragraphs: ["Ta fram uppgifter om elcentral, huvudsäkring, mätarskåp, tidigare elarbeten och om huset redan har laddbox, batterilager eller andra större laster. Ju bättre underlag installatören får, desto lättare blir det att bedöma vad som behöver kontrolleras på plats."] },
      { heading: "Bedöm central och kabelväg tidigt", paragraphs: ["Växelriktare, brytare och kablar behöver placeras så att lösningen är säker, åtkomlig och begriplig vid service. Om centralen är full, gammal eller otydligt märkt bör den bedömas innan solcellsprojektet låses till en viss teknisk lösning."] },
      { heading: "Frågor att ställa före offert", paragraphs: ["Be leverantören beskriva hur anslutningen ska göras, vilken dokumentation som lämnas, vem som utför elinstallationsarbetet och om företaget är registrerat för rätt verksamhet. Fråga också hur anläggningen stängs av och vad du som ägare ska kontrollera efter driftsättning."], steps: ["Samla gruppförteckning och uppgifter om huvudsäkring.", "Beskriv befintlig laddbox, värmepump eller större laster.", "Fråga vem som ansvarar för elinstallationsarbetet.", "Spara offert, ritning och driftinformation."] },
      { heading: "Planera för framtida ändringar", paragraphs: ["Solceller kan senare kombineras med batterilager, laddbox eller ändrad elförbrukning. Det betyder inte att allt måste installeras direkt, men projekteringen bör ta höjd för serviceutrymme, dokumentation och tydlig märkning från början."] },
    ],
    sourceLabel: "Elsäkerhetsverket: Solceller",
    sourceUrl: "https://www.elsakerhetsverket.se/privatpersoner/din-elanlaggning/bygga-och-renovera/installation-av-solceller/",
  },
  {
    slug: "el-markning-hemma",
    title: "El märkning hemma – märk elcentral, grupper och brytare rätt",
    description: "Rätt elmärkning gör bostaden säkrare och hjälper elektrikern vid felsökning, renovering och framtida arbeten.",
    category: "Elcentral",
    readTime: "5 min läsning",
    publishedAt: "2026-08-23",
    updatedLabel: "Uppdaterad 23 augusti 2026",
    accent: "blue",
    intro: "Tydlig märkning i elcentralen gör stor skillnad när ett fel ska avgränsas eller när en elektriker behöver arbeta i bostaden. Om grupper, brytare och installerad utrustning är otydliga tar felsökning längre tid och risken för fel antaganden ökar.",
    safetyNote: "Märk aldrig om en grupp genom att gissa. Om du inte vet vad en säkring eller brytare matar ska ett registrerat elföretag hjälpa till att kontrollera och märka rätt.",
    sections: [
      { heading: "Vad bör vara märkt?", paragraphs: ["Gruppförteckningen bör visa vilka rum eller funktioner varje säkring påverkar. Särskild utrustning som laddbox, solceller, golvvärme, värmepump och utomhusmatning bör vara lätt att identifiera för den som ska felsöka eller bryta rätt del."] },
      { heading: "När ska märkningen uppdateras?", paragraphs: ["Efter renovering, ny installation, byte av central eller ändrade grupper bör märkningen ses över. Detsamma gäller om du märker att en säkring inte stämmer med texten, eller om flera gamla anteckningar gör centralen svår att förstå."] },
      { heading: "Så tar du fram bättre underlag", paragraphs: ["Du kan själv notera vad som slocknar när en känd grupp bryts enligt centralens normala användning, men gör inte upprepade tester om skydd löser ut på grund av fel. Vid osäkerhet eller otydlig central är professionell kontroll bättre än hemmagissningar."], steps: ["Fotografera befintlig märkning.", "Skriv ner vilka rum och funktioner som verkar höra ihop.", "Be elektrikern kontrollera och uppdatera märkningen efter arbete.", "Spara dokumentationen digitalt."] },
      { heading: "Märkning hjälper vid akut elfel", paragraphs: ["Vid bränd lukt, vatten, strömlösa delar av bostaden eller återkommande säkringsfel kan tydlig märkning hjälpa både dig och elektrikern att beskriva situationen. Den ersätter inte felsökning, men gör första bedömningen snabbare och säkrare."] },
    ],
    sourceLabel: "Elsäkerhetsverket: Dokumentation och märkning",
    sourceUrl: "https://www.elsakerhetsverket.se/privatpersoner/anlita-ett-elinstallationsforetag/dokumentation-och-markning/",
  },
  {
    slug: "omdragning-av-el",
    title: "Omdragning av el i hus eller lägenhet – när krävs det och vad ingår?",
    description: "Vid äldre el, renovering eller nya behov kan el behöva dras om. Här är vad som påverkar omfattning, pris och planering.",
    category: "Renovering",
    readTime: "6 min läsning",
    publishedAt: "2026-08-23",
    updatedLabel: "Uppdaterad 23 augusti 2026",
    accent: "amber",
    intro: "Omdragning av el kan betyda allt från några nya ledningar i ett rum till en större modernisering av en äldre elanläggning. Behovet avgörs av anläggningens skick, hur bostaden ska användas och vilka delar som ska byggas om.",
    safetyNote: "Dra inte nya kablar, flytta dosor eller ändra fasta elledningar själv. Omdragning av el är elinstallationsarbete och ska utföras av registrerat elföretag.",
    sections: [
      { heading: "När blir omdragning aktuellt?", paragraphs: ["Vanliga skäl är äldre installation med brister, renovering där väggar öppnas, nya köks- eller badrumsfunktioner, fler fasta uttag, golvvärme, laddbox eller återkommande fel som visar att befintlig lösning inte räcker."] },
      { heading: "Delvis eller större arbete", paragraphs: ["Ibland räcker det att dra om el i ett rum eller till en viss funktion. I andra fall behöver elcentral, gruppindelning och flera kabelvägar planeras om. En seriös offert bör beskriva vad som ingår, vad som är antaganden och vilka ytor som behöver öppnas."] },
      { heading: "Det här påverkar priset", paragraphs: ["Pris påverkas av bostadens ålder, åtkomst i väggar och tak, antal elpunkter, centralens skick, krav på återställning och om andra hantverkare behöver samordnas. Därför är bilder, ritning och tydlig rumsbeskrivning värdefulla inför första bedömningen."], steps: ["Beskriv vilka rum som ska ändras.", "Samla bilder på elcentral och befintliga uttag.", "Fråga vad som ingår i märkning och dokumentation.", "Planera elarbetet innan väggar stängs."] },
      { heading: "Spara dokumentationen efteråt", paragraphs: ["När el har dragits om ska du förstå vad som har ändrats och hur centralen är märkt. Spara gruppförteckning, produktinformation och uppgifter om utförande företag. Det förenklar felsökning, försäljning och framtida renoveringar."] },
    ],
    sourceLabel: "Elsäkerhetsverket: Bygga och renovera",
    sourceUrl: "https://www.elsakerhetsverket.se/privatpersoner/din-elanlaggning/bygga-och-renovera/",
  },
];
