import type { GuidePost } from "./posts";

export const batchGuidePosts: GuidePost[] = [
  {
    slug: "laddstolpe-pa-jobbet-eller-parkeringshus",
    publishedAt: "2026-08-09",
    updatedLabel: "Uppdaterad 9 augusti 2026",
    title: "Ladda elbilen på jobbet eller i parkeringshuset – vad gäller?",
    description: "Skillnaden mellan att ladda via en delad laddstolpe hos arbetsgivaren eller i ett parkeringshus jämfört med hemmaladdning, och vad du bör kontrollera.",
    category: "Elbilsladdning",
    readTime: "4 min läsning",
    accent: "blue",
    intro: "Fler laddar elbilen på arbetsplatsen eller i ett garage med delade laddstolpar snarare än hemma. Anläggningen ägs och underhålls då av någon annan, men du som användare har fortfarande ett ansvar för hur du ansluter och vilken utrustning du använder.",
    safetyNote: "Använd inte en laddstolpe som ser skadad ut, har spruckna kontakter eller där kabeln ligger löst på marken – anmäl den till fastighetsägaren eller ansvarig operatör i stället för att chansa på anslutningen.",
    sections: [
      { heading: "Vem ansvarar för anläggningen", paragraphs: ["En laddstolpe på en arbetsplats eller i ett parkeringshus ingår i fastighetens elanläggning och underhålls normalt av fastighetsägaren eller den operatör som driver laddtjänsten. Du som användare ansvarar för din egen bils laddkabel om du använder en typ 2-kabel du själv tar med, samt för att inte belasta uttaget på ett sätt det inte är avsett för.", "Om laddstolpen har ett inbyggt kabel som sitter fast i stolpen, är det operatörens ansvar att den är hel och säker att ansluta."] },
      { heading: "Kontrollera innan du ansluter", paragraphs: ["Titta efter synliga skador på kontakt, kabel och själva stolpen innan du kopplar in bilen. En laddstolpe som är het, missfärgad eller där locket till uttaget inte sluter tätt ska inte användas."], steps: ["Kontrollera att kontakt och lock är hela och stänger ordentligt.", "Se att kabeln inte ligger i vatten eller är klämd.", "Anmäl skador till fastighetsägaren eller operatören innan du använder stolpen igen."] },
      { heading: "Delad kapacitet på flera laddstolpar", paragraphs: ["Många fastigheter med flera laddstolpar använder lastbalansering, vilket innebär att laddeffekten automatiskt kan sänkas när många laddar samtidigt. Det är en normal och avsedd funktion, inte ett fel, även om laddningen ibland känns långsammare vid högtrafik."] },
      { heading: "När behöver du elektriker", paragraphs: ["Som användare kontaktar du normalt fastighetsägaren eller operatören vid problem med en delad laddstolpe, inte en egen elektriker. Om du däremot planerar en egen laddbox hemma är det ett arbete som ett registrerat elinstallationsföretag ska utföra och bedöma utifrån din bostads elanläggning."] },
    ],
    sourceLabel: "Elsäkerhetsverket: Elbilsladdning",
    sourceUrl: "https://www.elsakerhetsverket.se/privatpersoner/din-elanlaggning/bygga-och-renovera/installation-av-elbilsladdare/",
  },
  {
    slug: "balkonguttag-hyresratt-vad-galler",
    publishedAt: "2026-08-10",
    updatedLabel: "Uppdaterad 10 augusti 2026",
    title: "Eluttag på balkongen i hyresrätten – vad får du ansluta?",
    description: "Så vet du vad ett balkonguttag i en hyresrätt tål, och varför fler produkter samtidigt kan bli ett problem du själv ansvarar för.",
    category: "Uthyrning",
    readTime: "4 min läsning",
    accent: "blue",
    intro: "En balkong i en hyresrätt har ofta ett eller ett par uttag avsedda för lättare bruk som belysning eller enstaka apparater, inte för allt du kan tänkas vilja koppla in. Vad du ansluter och hur, är ditt eget ansvar även om själva uttaget tillhör fastigheten.",
    safetyNote: "Använd bara utomhusklassad utrustning på ett balkonguttag och lämna inte grenuttag eller sladdar oskyddade för regn – fukt i en skarv eller kontakt kan orsaka ett farligt fel även om allt fungerade dagen innan.",
    sections: [
      { heading: "Fastighetens respektive ditt ansvar", paragraphs: ["Själva uttaget, kabeldragningen till det och eventuell jordfelsbrytare för kretsen är fastighetsägarens ansvar att hålla i skick. Det du kopplar in, från belysningsslingor till en grill med elstart, är ditt eget ansvar att välja rätt utrustning för."] },
      { heading: "Vad ett balkonguttag ofta inte är dimensionerat för", paragraphs: ["Flera balkonguttag är avsedda för lättare belastning och delar ibland grupp med närliggande lägenheter. Att samtidigt köra värmefläkt, belysning och laddning av flera produkter via grenuttag kan göra att säkringen löser ut betydligt oftare än vad som känns rimligt.", "Om detta händer regelbundet är det ett tecken på att belastningen är för hög för kretsen, inte nödvändigtvis ett fel i installationen."] },
      { heading: "Väder och fukt", paragraphs: ["Uttag och kontakter utomhus utsätts för regn, snö och temperaturväxlingar på ett annat sätt än inomhusuttag. Kontrollera att lock och tätningar sitter som de ska och koppla ur produkter som inte används, i stället för att låta dem sitta permanent anslutna i alla väder."], steps: ["Kontrollera att uttagets lock sluter tätt.", "Använd bara utomhusklassad kabel och utrustning.", "Koppla ur det som inte används, särskilt inför regn eller snö."] },
      { heading: "När behöver du elektriker", paragraphs: ["Anmäl återkommande utlösningar, ett uttag som känns löst eller synlig fukt inuti till din hyresvärd, som i sin tur ska låta ett registrerat elinstallationsföretag bedöma kretsen. Försök inte själv öppna eller täta ett balkonguttag."] },
    ],
    sourceLabel: "Elsäkerhetsverket: Din elanläggning",
    sourceUrl: "https://www.elsakerhetsverket.se/privatpersoner/din-elanlaggning/",
  },
  {
    slug: "julgransbelysning-inomhus-sakerhet",
    publishedAt: "2026-08-11",
    updatedLabel: "Uppdaterad 11 augusti 2026",
    title: "Julgransbelysning inomhus – vad bör du kontrollera varje år?",
    description: "En årlig snabbkoll av ljusslingans sladd, kontakt och märkning innan den sätts upp igen efter ett år i förvaring.",
    category: "Belysning",
    readTime: "3 min läsning",
    accent: "amber",
    intro: "En ljusslinga som legat hopvirad i en låda ett helt år kan ha fått skador som inte syns direkt vid en snabb titt. En kort kontroll innan den tänds för säsongen minskar risken för ett elfel mitt i julfirandet.",
    safetyNote: "Tänd aldrig en ljusslinga med synligt skadad kabel, spruckna lamphållare eller om den luktar bränt redan vid anslutning – släng den i stället för att laga den provisoriskt.",
    sections: [
      { heading: "Kontrollera innan du sätter upp slingan", paragraphs: ["Rulla ut hela slingan och känn igenom kabeln efter veck, sprickor eller ställen där isoleringen ser tunn eller skadad ut. Titta även på kontakten och stickproppen efter missfärgning eller lösa delar, vilket kan tyda på tidigare överhettning."], steps: ["Rulla ut hela slingan och undersök kabeln.", "Kontrollera stickpropp och kontakt efter skador.", "Testa slingan en kort stund innan den sätts fast permanent på granen eller i fönstret."] },
      { heading: "Placering nära brännbart material", paragraphs: ["En julgran med torra barr och omgivande papper, tyg eller julklappar är brännbart material som inte bör vara i direkt kontakt med varma lamphållare. Håll ett visst avstånd och kontrollera regelbundet att grenar inte bänder mot slingan när granen torkar under helgerna."] },
      { heading: "Timer och obevakad drift", paragraphs: ["Använd gärna en timer så att belysningen inte lämnas påslagen hela natten eller när ingen är hemma under längre tid. Det minskar både energiåtgång och risken att en eventuell begynnande skada hinner utvecklas obevakad."] },
      { heading: "När behöver du elektriker", paragraphs: ["En trasig ljusslinga är i sig sällan ett ärende för en elektriker, den ska bytas ut. Kontakta däremot ett registrerat elinstallationsföretag om själva vägguttaget eller strömbrytaren du använder för belysningen känns varm, glappar eller ger gnistor vid anslutning."] },
    ],
    sourceLabel: "Elsäkerhetsverket: Belysning",
    sourceUrl: "https://www.elsakerhetsverket.se/privatpersoner/dina-elprodukter/produkter/belysning/",
  },
  {
    slug: "strykjarn-glomt-paslaget-risk",
    publishedAt: "2026-08-12",
    updatedLabel: "Uppdaterad 12 augusti 2026",
    title: "Glömt strykjärnet påslaget – hur stor är risken egentligen?",
    description: "Vad som faktiskt händer när ett strykjärn eller liknande apparat med värmeelement lämnas påslaget, och hur du minskar risken i vardagen.",
    category: "Elsäkerhet hemma",
    readTime: "3 min läsning",
    accent: "amber",
    intro: "De flesta moderna strykjärn har ett automatiskt avstängningsskydd som löser ut om järnet står stilla eller ligger platt en stund. Äldre eller enklare modeller saknar ofta den funktionen helt, vilket gör vanan att kontrollera innan du lämnar rummet viktigare.",
    safetyNote: "Lämna aldrig ett strykjärn eller en liknande värmeprodukt utan avstängningsskydd påslaget när du lämnar rummet eller bostaden, oavsett hur kort tid det gäller.",
    sections: [
      { heading: "Skillnaden mellan gammalt och nytt strykjärn", paragraphs: ["Nyare strykjärn stänger ofta av sig själva automatiskt efter en viss tids stillastående, både stående och liggande. Ett äldre järn utan denna funktion fortsätter att vara varmt tills du själv stänger av det, vilket gör det viktigare att aldrig lämna det obevakat."] },
      { heading: "Bygg en enkel rutin", paragraphs: ["Koppla loss strykjärnet ur uttaget direkt efter användning i stället för att bara stänga av det på knappen, särskilt om du ofta blir avbruten eller glömmer bort saker. En sladd som är utdragen är ett tydligt, synligt tecken på att apparaten inte längre är strömförande."], steps: ["Dra ur kontakten direkt efter avslutad strykning.", "Ställ apparaten på ett stabilt, brandsäkert underlag medan den svalnar.", "Kontrollera avstängningsfunktionen genom tillverkarens bruksanvisning om du är osäker på om den finns."] },
      { heading: "Andra apparater med samma risk", paragraphs: ["Samma resonemang gäller för andra produkter med öppet värmeelement som hårstyling, brödrostar och vissa värmeplattor. Kontrollera i bruksanvisningen om produkten har ett automatiskt avstängningsskydd, och behandla den som om den saknade det om du är osäker."] },
      { heading: "När behöver du elektriker", paragraphs: ["Ett strykjärn som luktar bränt, ger gnistor eller där sladden är skadad ska tas ur bruk direkt och inte repareras själv. Kontakta i stället ett registrerat elinstallationsföretag om problemet i stället verkar sitta i det fasta uttaget, till exempel om det blir varmt eller gnistrar vid anslutning."] },
    ],
    sourceLabel: "Elsäkerhetsverket: Dina elprodukter",
    sourceUrl: "https://www.elsakerhetsverket.se/privatpersoner/dina-elprodukter/anvanda-elprodukter/",
  },
  {
    slug: "elcykel-lastcykel-batteri-laddning",
    publishedAt: "2026-08-13",
    updatedLabel: "Uppdaterad 13 augusti 2026",
    title: "Ladda elcykel eller lastcykel hemma – vad bör du tänka på?",
    description: "Praktiska råd för att ladda elcykelns eller lastcykelns litiumbatteri säkert hemma, i förråd eller i trapphus.",
    category: "Batterier",
    readTime: "4 min läsning",
    accent: "amber",
    intro: "Elcyklar och lastcyklar med litiumjonbatterier har blivit vanliga för både pendling och barntransport. Batteriet och laddaren behöver hanteras med samma försiktighet som andra större litiumbatterier, särskilt eftersom cykeln ofta laddas i ett trapphus, förråd eller nära andra brännbara föremål.",
    safetyNote: "Ladda inte ett batteri som är buckligt, svullet eller skadat efter en krock, och lämna aldrig laddningen helt obevakad i ett gemensamt trapphus eller en flyktväg.",
    sections: [
      { heading: "Välj rätt plats för laddning", paragraphs: ["Ladda helst på en plats där du har uppsikt och där ett eventuellt fel inte blockerar en utrymningsväg, exempelvis ett trapphus eller en smal korridor. Undvik att ladda direkt på brännbart underlag som en trämatta eller nära gardiner och andra tyger."], steps: ["Välj en laddplats med uppsikt och fri från brännbart material.", "Kontrollera att batteriet inte är skadat innan du ansluter laddaren.", "Använd bara den laddare som är avsedd för cykeln eller batteriet."] },
      { heading: "Använd rätt laddare och kabel", paragraphs: ["Använd den laddare som följde med cykeln eller en som uttryckligen är godkänd av tillverkaren för det specifika batteriet. En felaktig eller inkompatibel laddare kan ge fel laddström och öka risken för överhettning."] },
      { heading: "Efter en krock eller ett fall", paragraphs: ["Ett batteri som varit med om en kraftig stöt, till exempel vid en cykelolycka, kan ha inre skador som inte syns utanpå. Ladda inte ett sådant batteri förrän det bedömts av tillverkarens service eller en fackman, även om cykeln i övrigt verkar fungera som vanligt."] },
      { heading: "När behöver du elektriker", paragraphs: ["Själva batteriet och laddaren är sällan ett ärende för en elektriker, utan för cykelns återförsäljare eller tillverkarens service. Kontakta i stället ett registrerat elinstallationsföretag om det uttag du laddar via i garage eller förråd känns varmt, löser ut ofta eller om du planerar en fast laddplats för flera cyklar."] },
    ],
    sourceLabel: "Elsäkerhetsverket: Batterier",
    sourceUrl: "https://www.elsakerhetsverket.se/privatpersoner/dina-elprodukter/produkter/batterier/",
  },
  {
    slug: "poolvarme-vintertid-frysrisk-el",
    publishedAt: "2026-08-14",
    updatedLabel: "Uppdaterad 14 augusti 2026",
    title: "Poolvärme och pumpar under vintern – vad händer om det fryser?",
    description: "Så skyddar du poolens eldrivna pump och värmesystem mot frostskador när anläggningen vintertid ska stängas ner eller hållas igång.",
    category: "Pool och spabad",
    readTime: "4 min läsning",
    accent: "blue",
    intro: "En pool med eldriven cirkulationspump och eventuell värmepump behöver hanteras annorlunda när temperaturen sjunker under nollan. Fel hantering kan skada både elektriska komponenter och rörsystem, och i värsta fall skapa en osäker anläggning till våren.",
    safetyNote: "Bryt strömmen till pumpen och eventuell värmepump innan du utför vinterförberedelser för hand, och rör aldrig elektrisk utrustning vid poolen med våta händer eller fötter.",
    sections: [
      { heading: "Stänga ner för säsongen", paragraphs: ["Om poolen inte ska användas under vintern behöver cirkulationspumpen och tillhörande elektrisk utrustning normalt stängas av och skyddas enligt tillverkarens anvisningar. Se till att eluttag och kopplingar täcks eller skyddas från fukt och is under den tid anläggningen står oanvänd."] },
      { heading: "Om pumpen ska gå även vintertid", paragraphs: ["Vissa anläggningar kräver att pumpen går kontinuerligt även vintertid för att undvika att vatten fryser och spränger rör. Kontrollera i så fall att elanslutningen är avsedd för utomhusbruk året runt och att jordfelsbrytaren för kretsen fungerar som den ska."],"steps":["Kontrollera tillverkarens rekommendation för vinterdrift.","Se till att elutrustningen är skyddad från is och snö.","Testa jordfelsbrytaren om den går att komma åt säkert."]},
      { heading: "Tecken på frostskada", paragraphs: ["Sprickor i kopplingsdosor, en pump som låter annorlunda vid start, eller synlig is runt elektriska anslutningar är tecken på att något kan ha frusit och skadats. Starta inte upp en misstänkt frostskadad pump innan den kontrollerats."] },
      { heading: "När behöver du elektriker", paragraphs: ["Kontakta ett registrerat elinstallationsföretag inför säsongsstart om du sett tecken på frostskador, om jordfelsbrytaren löst ut under vintern, eller om du planerar en ny fast elinstallation för pump eller värmepump vid poolen."] },
    ],
    sourceLabel: "Elsäkerhetsverket: El vid pool och spabad",
    sourceUrl: "https://www.elsakerhetsverket.se/privatpersoner/din-elanlaggning/bygga-och-renovera/",
  },
  {
    slug: "sälja-el-fran-solceller-vad-galler",
    publishedAt: "2026-08-15",
    updatedLabel: "Uppdaterad 15 augusti 2026",
    title: "Sälja överskottsel från solceller – vad behöver elektrikern koppla in?",
    description: "Skillnaden mellan att bara producera el till eget bruk och att mata ut överskott på nätet, och varför inkopplingen då ställer extra krav.",
    category: "Solceller",
    readTime: "5 min läsning",
    accent: "blue",
    intro: "Många solcellsägare vill sälja det överskott de inte förbrukar själva till elnätet. Det ställer andra krav på inkopplingen än en anläggning som bara är byggd för egen förbrukning, och det är inget du ska försöka ordna på egen hand efter att installationen redan är klar.",
    safetyNote: "Gör inga egna ändringar i kopplingen mellan solcellsanläggningen och elnätet för att aktivera överskottsförsäljning – felaktig utmatning kan vara farlig för personer som arbetar på elnätet.",
    sections: [
      { heading: "Produktion för eget bruk kontra utmatning", paragraphs: ["En anläggning som bara är byggd för egen förbrukning matar inte ut överskott på elnätet, utan eventuellt överskott går förlorat om det inte lagras. Ska du sälja överskott krävs en mätare som kan mäta i båda riktningarna samt ett avtal med ditt elnätsbolag och elhandelsbolag."] },
      { heading: "Anmälan till elnätsbolaget", paragraphs: ["Elnätsbolaget behöver godkänna och registrera anläggningen innan utmatning på nätet är tillåten. Det är normalt din elinstallatör som sköter den tekniska anmälan i samband med installationen eller vid en senare uppgradering."],"steps":["Kontakta ditt elnätsbolag om anmälan för utmatning.","Låt elinstallatören uppdatera eller installera rätt mätarutrustning.","Teckna avtal med ett elhandelsbolag för försäljning av överskottet."]},
      { heading: "Säkerhetskrav vid utmatning", paragraphs: ["En anläggning som matar ut el på nätet måste ha fungerande skydd som automatiskt kopplar bort produktionen vid ett strömavbrott, så att elnätspersonal inte riskerar att arbeta på en ledning som ändå är spänningssatt från din anläggning. Detta skydd ska vara testat och godkänt som en del av installationen."] },
      { heading: "När behöver du elektriker", paragraphs: ["Kontakta ett registrerat elinstallationsföretag som är insatt i solcellsanläggningar innan du bestämmer dig för att sälja överskottsel, oavsett om anläggningen är ny eller redan installerad för egen förbrukning. Företaget kan bedöma vad som behöver kompletteras och sköta kontakten med elnätsbolaget."] },
    ],
    sourceLabel: "Elsäkerhetsverket: Solceller",
    sourceUrl: "https://www.elsakerhetsverket.se/privatpersoner/din-elanlaggning/bygga-och-renovera/installation-av-solceller/",
  },
  {
    slug: "hemmakontor-flera-skarmar-el-belastning",
    publishedAt: "2026-08-16",
    updatedLabel: "Uppdaterad 16 augusti 2026",
    title: "Hemmakontor med flera skärmar och datorer – räcker eluttagen?",
    description: "Så bedömer du om hemmakontorets uttag och grenuttag klarar flera skärmar, datorer och laddare samtidigt utan att bli en risk.",
    category: "Hemmakontor",
    readTime: "4 min läsning",
    accent: "blue",
    intro: "Ett hemmakontor med flera skärmar, en dockningsstation, högtalare och laddare för olika enheter drar sammantaget mer ström än vad ett enda uttag ofta är tänkt för. De flesta av dessa apparater drar var för sig lite ström, men den sammanlagda mängden sladdar och kopplingar kan bli ett problem om den hanteras fel.",
    safetyNote: "Koppla inte flera grenuttag i följd efter varandra för att få plats med all utrustning – det kallas att stapla grenuttag och ökar risken för överhettning i kontakterna.",
    sections: [
      { heading: "Skilj på ström och antal kontakter", paragraphs: ["Skärmar, datorer och laddare drar var för sig oftast lite effekt, så problemet är sällan den totala strömmen utan snarare dåligt organiserade kablar och överbelastade grenuttag. Ett kvalitetsgrenuttag med överbelastningsskydd är säkrare än flera billiga grenuttag kopplade i kedja."] },
      { heading: "Ordna kablar och kontakter", paragraphs: ["Låt sladdar hänga fritt i stället för att pressas ihop i en tät bunt bakom skrivbordet, eftersom värme kan byggas upp om många kablar ligger tätt hoptvinnade under lång tid. Dra inte kablar under mattor eller där de kan klämmas av möbler."],"steps":["Använd ett grenuttag med överbelastningsskydd i stället för flera i kedja.","Låt kablar ligga löst, inte hoptvinnade i en tät bunt.","Kontrollera regelbundet att kontakter och grenuttag inte känns varma."]},
      { heading: "Om säkringen löser ut", paragraphs: ["Löser säkringen ut när flera skärmar och laddare startar samtidigt kan det bero på att gruppen delas med andra apparater i hemmet, som exempelvis köksmaskiner. Notera vad som var igång samtidigt och undvik att starta allt på en gång i väntan på en eventuell bedömning."] },
      { heading: "När behöver du elektriker", paragraphs: ["Kontakta ett registrerat elinstallationsföretag om ett uttag eller grenuttag blir varmt vid normal användning, om säkringen löser ut regelbundet, eller om du vill ha fler fasta uttag installerade för ett permanent hemmakontor."] },
    ],
    sourceLabel: "Elsäkerhetsverket: Dina elprodukter",
    sourceUrl: "https://www.elsakerhetsverket.se/privatpersoner/dina-elprodukter/anvanda-elprodukter/",
  },
  {
    slug: "belysning-timer-bortavaro-inbrottsskydd",
    publishedAt: "2026-08-17",
    updatedLabel: "Uppdaterad 17 augusti 2026",
    title: "Styra belysning med timer vid bortavaro – vad bör du tänka på elmässigt?",
    description: "Så väljer och ansluter du timerstyrd belysning som ska se ut att vara hemma vid semester eller bortavaro, utan att det blir en elrisk.",
    category: "Smarta hem",
    readTime: "3 min läsning",
    accent: "blue",
    intro: "Timerstyrd belysning som tänds och släcks automatiskt är ett vanligt sätt att signalera att någon är hemma, men produkten och den anslutna belysningen behöver vara rätt matchade för att kunna vara igång obevakat under en längre period.",
    safetyNote: "Använd inte en timer eller smart kontakt tillsammans med en lampa eller ljuskälla som blir mycket varm, till exempel en äldre halogenlampa, om produkten inte uttryckligen är avsedd för det.",
    sections: [
      { heading: "Välj rätt typ av timer", paragraphs: ["En timer som ansluts i vägguttaget mellan lampan och kontakten passar för fristående lampor, medan en fast installerad timerstyrd strömbrytare krävs för tak- eller väggmonterad belysning. Blanda inte ihop de två lösningarna eller försök koppla in en produkt avsedd för fristående bruk på en fast installation."] },
      { heading: "Tänk på belastning över tid", paragraphs: ["En produkt som ska stå obevakad och tändas flera gånger per dygn under en semesterperiod bör vara av god kvalitet och inte redan visa tecken på slitage. Testa gärna funktionen några dagar innan du reser, så att du vet att den fungerar som tänkt."],"steps":["Testa timern eller den smarta kontakten några dagar i förväg.","Kontrollera att ansluten lampa är avsedd för längre tids obevakad drift.","Undvik att kombinera flera produkter i samma grenuttag för denna funktion."]},
      { heading: "Kombinera inte med riskfyllda produkter", paragraphs: ["Koppla inte in värmeprodukter som element eller liknande på en timer avsedd för belysning i syfte att simulera aktivitet i hemmet. Sådana produkter ska aldrig lämnas att styras automatiskt utan uppsikt om de inte är specifikt konstruerade och godkända för det."] },
      { heading: "När behöver du elektriker", paragraphs: ["En fast installerad timerfunktion för belysning, exempelvis kopplad till en befintlig strömbrytare, är ett arbete för ett registrerat elinstallationsföretag. Kontakta även elektriker om du vill styra flera ljuspunkter i hemmet centralt och är osäker på hur den befintliga installationen är uppbyggd."] },
    ],
    sourceLabel: "Elsäkerhetsverket: Belysning",
    sourceUrl: "https://www.elsakerhetsverket.se/privatpersoner/dina-elprodukter/produkter/belysning/",
  },
  {
    slug: "dubbelboende-sommarhus-el-underhall-vinter",
    publishedAt: "2026-08-18",
    updatedLabel: "Uppdaterad 18 augusti 2026",
    title: "Bor du växelvis på två ställen? Så håller du koll på elen i det tomma hemmet",
    description: "Praktiska rutiner för dig som pendlar mellan två bostäder och behöver hålla koll på elanläggningen i det hem som står tomt.",
    category: "Fritidshus",
    readTime: "4 min läsning",
    accent: "blue",
    intro: "Att växla mellan två bostäder, till exempel stad och fritidshus eller vid växelvis boende, innebär att en av bostäderna ofta står obevakad under längre perioder. Det gör regelbundna kontroller av elanläggningen viktigare än i ett hem som alltid är bebott.",
    safetyNote: "Lämna inte elprodukter med värmeelement, som element eller vattenkokare, inkopplade i ett hem som ska stå tomt en längre tid, även om de har egna säkerhetsfunktioner.",
    sections: [
      { heading: "Innan du lämnar bostaden tom", paragraphs: ["Gå igenom vilka apparater som verkligen behöver vara igång, som kyl, frys och eventuell frostvakt, och koppla ur eller stäng av det som inte behövs. En snabb koll av elcentralen efter tecken på värme, lukt eller missfärgning tar bara någon minut men kan upptäcka begynnande problem tidigt."],"steps":["Dra ur eller stäng av apparater som inte behöver vara igång.","Kontrollera elcentralen efter tecken på värme eller missfärgning.","Notera vem som har regelbunden tillsyn under din frånvaro."]},
      { heading: "Regelbunden tillsyn", paragraphs: ["Be en granne, familjemedlem eller ett tillsynsföretag titta till bostaden med jämna mellanrum om du är borta under längre sammanhängande perioder. Tydliga instruktioner om vad de ska kontrollera, och vem de ska kontakta vid ett upptäckt problem, gör tillsynen mer värd."] },
      { heading: "Årstidsväxling och uppvärmning", paragraphs: ["En bostad som står kall under vintern riskerar fuktskador som i sin tur kan påverka elinstallationen, särskilt vid källare och krypgrund. Om du håller viss värme igång under bortavaron, se till att den lösningen är avsedd för obevakad, kontinuerlig drift."] },
      { heading: "När behöver du elektriker", paragraphs: ["Kontakta ett registrerat elinstallationsföretag om tillsynen upptäcker tecken på fukt, skador eller lukt kring elcentralen, eller om du vill installera en fjärrövervakad lösning som varnar dig vid strömavbrott eller andra avvikelser i det tomma hemmet."] },
    ],
    sourceLabel: "Elsäkerhetsverket: Du är ansvarig för elen",
    sourceUrl: "https://www.elsakerhetsverket.se/privatpersoner/du-ar-ansvarig-for-elen/",
  },
];
