import { eq } from "drizzle-orm";
import { getDb } from "../../../../db";
import { guidePosts as guidePostsTable } from "../../../../db/schema";
import { autoGuideTemplates, createAutoGuidePost } from "../../../guider/auto-posts";

export const runtime = "nodejs";

function authorized(request: Request) {
  const expected = process.env.CRON_SECRET?.trim();
  const header = request.headers.get("authorization");
  return Boolean(expected) && header === `Bearer ${expected}`;
}

export async function GET(request: Request) {
  if (!authorized(request)) {
    return Response.json({ error: "Unauthorized" }, { status: 401 });
  }

  const now = new Date();
  const bucket = Math.floor(now.getTime() / (5 * 60 * 1000));
  const templateIndex = bucket % autoGuideTemplates.length;
  const db = getDb();

  let post = createAutoGuidePost(now, templateIndex);
  for (let offset = 0; offset < autoGuideTemplates.length; offset += 1) {
    const candidate = createAutoGuidePost(now, templateIndex + offset);
    const [existing] = await db.select({ id: guidePostsTable.id }).from(guidePostsTable).where(eq(guidePostsTable.slug, candidate.slug)).limit(1);
    if (!existing) {
      post = candidate;
      break;
    }

    if (offset === autoGuideTemplates.length - 1) {
      return Response.json({ ok: true, created: false, slug: candidate.slug, message: "Alla automatiska inlägg finns redan." }, { headers: { "Cache-Control": "no-store" } });
    }
  }

  const [created] = await db.insert(guidePostsTable).values({
    slug: post.slug,
    title: post.title,
    description: post.description,
    category: post.category,
    readTime: post.readTime,
    publishedAt: new Date(post.publishedAt),
    updatedLabel: post.updatedLabel,
    accent: post.accent,
    intro: post.intro,
    safetyNote: post.safetyNote,
    sections: post.sections,
    sourceLabel: post.sourceLabel,
    sourceUrl: post.sourceUrl,
    autoGenerated: true,
    createdAt: now,
    updatedAt: now,
  }).returning({ slug: guidePostsTable.slug });

  return Response.json({ ok: true, created: Boolean(created), slug: post.slug }, { headers: { "Cache-Control": "no-store" } });
}
